### PR TITLE
Update access-tokens.md

### PR DESCRIPTION
**Pull request by vuvasira**
Added the section for the new settings Protect access to repositories in YAML pipelines.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@vuvasira : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AnnaMHuff** [comment]
@vijayma  - Can you review the proposed changes?

*NOTE*: On Line 184 of the changes, a word or words seem to be missing from the following phrase: 

- "in the previous section, For the YAML pipelines provides a".

Please revise as needed for clarity and understanding.

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

Thanks!

#label:"aq-pr-triaged"

**Comment by vijayma** [comment]
@steved0x the text in this PR needs some edits. Can you please help with this?

**Comment by steved0x** [comment]
#hold-off

**Comment by patest-dev** [comment]
There is typo in the new text. `yanml` should read `yaml`  I guess

**Comment by PRMerger13** [comment]
@vuvasira : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request closed without merging**
