### PR TITLE
Updated "Delay task" YAML snippet

### PR DESCRIPTION
**Pull request by dmitrykurmanov**
Updated "Delay task" YAML snippet for the better understanding

### CODE REVIEW

**Comment by dmitrykurmanov** [comment]
related to https://github.com/MicrosoftDocs/vsts-docs/issues/4082

**Comment by ktoliver** [comment]
@RoopeshNair - Could you review this PR? The include file is used in your article https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delay?view=azure-devops.

Thanks.

**Comment by ktoliver** [comment]
close/reopen for labeling

**Comment by Jak-MS** [comment]
@RoopeshNair - bump. take a look? thanks.

**Comment by ktoliver** [comment]
> ```
> steps:
>    - task: Delay@1
>      inputs:
>          delayForMinutes: '1'
> ```
> 
> still getting below error on azure pipeline. How to resolve?
> 
> **Step references task 'Delay' at version '1.1.10' which is not valid for the given job target**

@jigisha9 To be sure that the concern is seen, you might choose to create a new issue: https://github.com/MicrosoftDocs/azure-devops-docs/issues.

**Pull request merged**
