### PR TITLE
Update install-ssh-key.md

### PR DESCRIPTION
**Pull request by arammaliachi**
We got a user in the support team saying he struggled to figure out how to configure this.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@arammaliachi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@arammaliachi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@vijayma Would you review this pull request? Thank you.

**Comment by ktoliver** [comment]
@vijayma @steved0x - Could you review this community contribution pipelines pull request? Thanks.

**Comment by steved0x** [comment]
@ktoliver I'll take a look, thank you.

**Comment by steved0x** [comment]
#reassign steved0x

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@steved0x: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@steved0x - Thanks for reviewing the pull request. It looks like the first part of the article has been substantially updated since the PR was opened. I resolved the merge conflict, and thus added the section that's new in this PR to what's current in master. Is the end result still good to go (merge)? Thanks.

**Pull request merged**
