### PR TITLE
Updated the  CASE REVIEW #1758717

### PR DESCRIPTION
**Pull request by v-abiss**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@v-abiss : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
#sign-off

I think that node should not be capitalized but we can fix that later.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@juliakm I made a couple punctuation and formatting edits, so I changed the capitalization of "node," also. Merging now.

**Pull request merged**
