### PR TITLE
Added more info about permissions

### PR DESCRIPTION
**Pull request by DenisRumyantsev**
This PR provides docs about information security for [self-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#permissions).

### CODE REVIEW

**Comment by PRMerger7** [comment]
@DenisRumyantsev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@DenisRumyantsev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@DenisRumyantsev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@DenisRumyantsev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@DenisRumyantsev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@DenisRumyantsev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@DenisRumyantsev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by anatolybolshakov — APPROVED** [review]

**Review by alexander-smolyakov — APPROVED** [review]

**Comment by DenisRumyantsev** [comment]
This PR was transferred to [another repo](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/3510).

**Pull request closed without merging**
