### PR TITLE
Adding note to associating builds to manual test results

### PR DESCRIPTION
**Pull request by JPGRodrigues**
The note is related to DTS https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1834314 .
While waiting for the fix to be published the public documentation should clearly identify this limitation.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@JPGRodrigues : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by steved0x — APPROVED** [review]

**Comment by PRMerger13** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
