### PR TITLE
[TFVC] Add Reconcile command

### PR DESCRIPTION
**Pull request by DmitriyKirakosyan**
https://github.com/MicrosoftDocs/azure-devops-docs/issues/1066
https://github.com/MicrosoftDocs/azure-devops-docs/issues/1561

### CODE REVIEW

**Comment by PRMerger14** [comment]
@DmitriyKirakosyan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MaximMalygin — APPROVED** [review]

**Comment by ktoliver** [comment]
Hi @DmitriyKirakosyan - New articles should be submitted in the private repo so that they can benefit from standard quality checks that aren't available in the public repo. It looks like you should have access to the private repo. Would you submit this in a pull request in the private repo? We'll close this PR. Note that the links to msdn are redirecting because MSDN content is no longer available. It'd be best to use the current links instead of relying on redirects in new content. Thanks!

If you need info about working in the private repo, let me know and I'll send it in email.

-Kristine, PR review team

**Comment by ktoliver** [comment]
cc @mijacobs

**Comment by DmitriyKirakosyan** [comment]
Thanks @ktoliver! I'll do that.

**Pull request closed without merging**
