### PR TITLE
Add detail and Doc link for firewall rules in Azure KeyVault to enable Azure KeyVault Task to work from services

### PR DESCRIPTION
**Pull request by SamGrantham**
Some of KeyVault tasks connection and pulling of secrets is happening at pipeline edit time not only at pipeline run time.  Therefore, the IPs of the Org itself need to be added to the KeyVault firewall for this to work.  This *is* called out in the FAQ but it is not worded clearly and lacks a link to the relevant documents.

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@SamGrantham : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@RoopeshNair, 

Can you review the proposed changes? Note that, if approved, the "en-us" needs to be removed from the added URL.

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by rohit-batra — APPROVED** [review]

**Comment by SamGrantham** [comment]
Hi @jborsecnik,

I reached out to @RoopeshNair and he said he's no longer working with ADO/Github and asked me to tag @vijayma...

**Comment by Court72** [comment]
@steved0x 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Comment by PRMerger13** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
