### PR TITLE
Fix yml example in deployment-jobs.md

### PR DESCRIPTION
**Pull request by VyacheslavPritykin**
#10569

### CODE REVIEW

**Comment by PRMerger10** [comment]
@VyacheslavPritykin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TimShererWithAquent** [comment]
@juliakm for awareness

**Comment by juliakm** [comment]
@VyacheslavPritykin  Thank you for looking into this! Are you able to get your YAML to successfully run? I'm finding that StageB still gets skipped.

**Comment by VyacheslavPritykin** [comment]
@juliakm Well, I actually tested it in a scenario, when the variable is set inside the non-deployment job and that works:

```yml
- job: A1
  steps:
    - pwsh: echo "##vso[task.setvariable variable=RunStageB;isOutput=true]true"
      name: setvarStep
    - bash: echo $(System.JobName)
 ```

I can confirm that if a variable is set inside a `deployment` job, then it still does not work, so it looks like there is an issue not only in the documentation but also in the pipeline engine.

I'll update the PR  to have a non-deployment job A1, so at least the documentation will have a valid example.

Moreover, the snippet from the documentation has another flaw (probably you've already found it): `Job B1: Environment is required.` (I didn't find it initially, because I needed a stage condition for a non-deployment job)

**Comment by PRMerger16** [comment]
@VyacheslavPritykin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VyacheslavPritykin** [comment]
> I'll update the PR to have a non-deployment job A1, so at least the documentation will have a valid example.

I've updated and then I realized that it makes no sense since the page describes the Deployment Jobs and the difference in the syntax of consuming variables. We need to fix the initial version where a variable is set in the deployment job.

I've found how to fix the variable assignment in the second job:
```yml
myOutputVar: $[stageDependencies.StageA.A1.outputs['A1.setvarStep.RunStageB']]
myOutputVar: $[stageDependencies.StageA.A1.outputs['A1.setvarStep.RunStageB']]
```

but I'm still struggling with the valid condition expression

**Comment by juliakm** [comment]
Thanks @VyacheslavPritykin!

#sign-off

**Pull request merged**
