### PR TITLE
Typo "@RecentProjectActivity**"→"@RecentProjectActivity"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops

### CODE REVIEW

**Comment by PRMerger9** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@KathrynEE - Could you take a look at the notes section? The xref links don't appear as links on the [live site](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops#full-text-and-partial-word-searches); are they intended to?

image

They don't render at all in [GitHub Preview](https://github.com/MicrosoftDocs/azure-devops-docs/blob/216faf2a9805d1a70b8f419595bd01db2b8c6756/docs/boards/queries/query-operators-variables.md):

image

Would an edit pass to convert HTML usage in the article to Markdown make it easier to ensure that the intended formatting is displayed?

Thanks!

**Comment by KathrynEE** [comment]
@ktoliver - I'm not seeing a problem with any link in the Notes. Conversion of the HTML table is a good idea, but not top of my list at the moment.

**Review by KathrynEE — APPROVED** [review]

**Pull request merged**
