### PR TITLE
Update variable-groups.md

### PR DESCRIPTION
**Pull request by yaweriqbal**
Corrected error

Updated text for clarity

### CODE REVIEW

**Comment by PRMerger14** [comment]
@yaweriqbal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
The typo fixes look good; thanks!

**Pull request merged**
