### PR TITLE
Update Failing checkout section

### PR DESCRIPTION
**Pull request by kopetan-ms**
Replace Bitbucket Server with the correct value, Github Enterprise Server.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@kopetan-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kopetan-ms** [comment]
#9295

**Comment by ktoliver** [comment]
@steved0x  - Hi, could you review the proposed update to your article? Thanks!

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
