### PR TITLE
Moving the "Note" section higher in the page

### PR DESCRIPTION
**Pull request by DevOps-Guy**
The "Note" section that talks about the need for direct assignment of the role and groups wont work is present below in the page and sometimes users miss this part. So, moving it higher, so that users wont miss this critical piece of info.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@DevOps-Guy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chcomley — APPROVED** [review]

**Comment by chcomley** [comment]
#sign-off

**Comment by chcomley** [comment]
Thanks @DevOps-Guy!

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
