### PR TITLE
Update move-git-repos-between-team-projects.md

### PR DESCRIPTION
**Pull request by jay-dance-sh**
Changed png to uppercase to match the image filenames. The links to the pictures are currently broken.

### CODE REVIEW

**Comment by jay-dance-sh** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
Hi @jay-dance-sh,

Can you add a screenshot of where you're seeing broken images? They're currently rendering on the live site: https://learn.microsoft.com/azure/devops/repos/git/move-git-repos-between-team-projects?view=azure-devops

Thanks!

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Court72** [comment]
We'll close this PR for now, but we'll reopen it if an issue needs to be addressed.

**Comment by jay-dance-sh** [comment]
https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/move-git-repos-between-team-projects.md

***@***.***


Regards,
Jay Dance

**Pull request closed without merging**
