### PR TITLE
v-ryzube/build-release-custom-task

### PR DESCRIPTION
**Pull request by ZuberR97**
Added a step to add-build-task.md explaining how to create a build and release pipeline for an Azure DevOps custom task.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@ZuberR97 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chcomley** [comment]
#sign-off

**Comment by chcomley** [comment]
@ktoliver are you able to merge this PR please? I am not authorized. Thanks for your help!

**Comment by ktoliver** [comment]
> @ktoliver are you able to merge this PR please? I am not authorized. Thanks for your help!

Yes! Sure thing. I'll make a few edits and then merge. Thanks.

**Comment by ktoliver** [comment]
Actually, we'll need to move this commit to the private repo so we can rename the image file that uses uppercase letters; only lowercase letters, numbers, and hyphens are allowed in file names. There are some other blocking quality criteria that we can fix in the new PR, like removing locales from microsoft.com URLs. The original contributor will still be acknowledge as contributor. I'll do this later this morning.

**Comment by ktoliver** [comment]
@ZuberR97 @chcomley The commits in the PR were moved to private repo PR https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1644. The new PR will be assigned to @chcomley for review after blocking issues are resolved. We'll close this PR. Thanks.

**Comment by ktoliver** [comment]
Updated private repo PR: https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1779

We'll close this PR.

**Pull request closed without merging**
