### PR TITLE
Updating troubleshooting section

### PR DESCRIPTION
**Pull request by kanika1894**
While using templates from a BLOB, the template URL should have proper parameter, otherwise it deosn't let you download the template and proceed.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@kanika1894 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@kanika1894 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@kanika1894 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@kanika1894 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@RoopeshNair @steved0x @ramiMSFT - Could one of you review this pull request for Pipelines content? Thanks.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by steved0x — APPROVED** [review]

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
