### PR TITLE
Azure artifacts gradle documentation update

### PR DESCRIPTION
**Pull request by koldou98**
I have updated the Azure artifacts Gradle upload documentation, as I could not upload a Gradle artifact to Azure Artifacts with the documentation

### CODE REVIEW

**Comment by PRMerger13** [comment]
@koldou98 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by koldou98** [comment]
@ktoliver @ramiMSFT

Has it been any update?

**Comment by ktoliver** [comment]
@ramiMSFT - Could you review the proposed update to your article? Thanks.

**Comment by koldou98** [comment]
@ktoliver has it been any update?

**Comment by ktoliver** [comment]
@KathrynEE - Hi, could you recommend someone on the content team who can review this community contribution? Thanks.

**Comment by KathrynEE** [comment]
@ktoliver - @ramiMSFT is the correct reviewer. I'll ping him to take a look.

**Review by ramiMSFT — CHANGES_REQUESTED** [review]
Must be deleted first: create-feed.png, create-new-feed.png, gradle-feed-settings.png

**Comment by ktoliver** [comment]
@ramiMSFT Thanks for the review.

@koldou98 Your pull request includes three new image files that aren't referenced in article in the pull request. Are they included in the PR to show the bases of your suggested changes to the article? If the image files aren't referenced in an MD file, they'll need to be removed from the PR before it can be merged. Thanks!

**Comment by PRMerger18** [comment]
@koldou98 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by koldou98** [comment]
I have just deleted the images

**Comment by ktoliver** [comment]
@ramiMSFT Is the PR ready to merge or still in progress? Thanks.

**Review by ramiMSFT — APPROVED** [review]

**Comment by ramiMSFT** [comment]
@ktoliver @koldou98 Approved ✔ Thank you

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks, all.

**Pull request merged**
