### PR TITLE
Adding a Note about fetching before merging

### PR DESCRIPTION
**Pull request by ThomasMPorter**
This was brought up in this tweet: https://twitter.com/jerrynixon/status/1232720988187451392?s=20

The Visual Studio instructions do not say anything about fetching remote changes before merging.

I'm not married to the wording, so if there's a better way to say this, please comment (and fix any grammatical issues!)

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ThomasMPorter : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@apawast Would you review this pull request? Thanks.

**Comment by TimShererWithAquent** [comment]
@ktoliver - I don't know why you think I'd be the person to review this -

**Comment by ktoliver** [comment]
@TimShererWithAquent Thanks

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@steved0x: I'm sorry - only the author of this article, @apawast, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@steved0x Thanks for the review.

**Comment by ThomasMPorter** [comment]
Thanks!

**Pull request merged**
