### PR TITLE
Fixing the example

### PR DESCRIPTION
**Pull request by ManuelGalindo**
CSS Azure DevOps Support fixed the documentation, example created with the help of ArielMorales

seems the issues

#7401  
#5327
#5220

Can be fixed 

All the images are in here 

https://github.com/ManuelGalindo/images

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ManuelGalindo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ManuelGalindo** [comment]
Hello Team this have couple of months, is there something I can do to solve the problems or what I missed?

**Comment by ktoliver** [comment]
@vijayma Would you review this pull request and respond to the contributor? Thanks.

**Comment by ktoliver** [comment]
Hi @ManuelGalindo - The pull request has been assigned to the author to review the proposed update.

**Comment by ktoliver** [comment]
Flagging for review @vijayma 

If the content update is approved, I can move the commit to the private repo and fix formatting and style issues before merging.

**Comment by ktoliver** [comment]
@vijayma Thanks for the review! I'll move the commit to the private repo today to fix formatting, grammar, and spelling issues, and to view the update on staging before merging. I'll post the private repo PR number here, and then close this PR. #hold-off

**Comment by ktoliver** [comment]
The commit in this PR has been moved to https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/2003 in the private repo. The contributor attribution for the commit will be intact. The new PR will be merged soon. We'll close this PR. Thanks.

**Pull request closed without merging**
