### PR TITLE
Update aks-template.md with the whitelisting of IP addresses

### PR DESCRIPTION
**Pull request by v-abiss**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@v-abiss : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Edit for Microsoft style. @azooinmyluggage or @steved0x - Could you review the proposed update to this Pipelines article? Thanks.

**Review by azooinmyluggage — APPROVED** [review]

**Comment by ktoliver** [comment]
Thanks!

**Pull request merged**
