### PR TITLE
Fix docker load command in caching example

### PR DESCRIPTION
**Pull request by yogevyuval**
Docker load accepts no arguments, only input

### CODE REVIEW

**Comment by PRMerger20** [comment]
@yogevyuval : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by yogevyuval** [comment]
@ktoliver @chcomley @juliakm 
?

**Comment by ktoliver** [comment]
@ramiMSFT Could you review the proposed changes to your article? Thanks.

**Review by chcomley — APPROVED** [review]

**Comment by ktoliver** [comment]
Thanks @chcomley

**Pull request merged**
