### PR TITLE
Update azure-key-vault.md to whitelist the IP addresses

### PR DESCRIPTION
**Pull request by v-abiss**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@v-abiss : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Edited for Microsoft style. @RoopeshNair or @steved0x - Could you review the proposed changes to this Pipelines article? Thanks.

**Comment by PRMerger15** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
