### PR TITLE
Add restoreArguments parameter

### LINKED ISSUE #8352: Missing argument description for: restoreArguments
```json
{
    "name": "restoreArguments",
    "type": "string",
    "label": "Arguments",
    "defaultValue": "",
    "visibleRule": "command = restore",
    "required": false,
    "helpMarkDown": "Write the additional arguments to be passed to **restore** command."
}
```

Source: [DotNetCoreCLIV2/task.json#L128-L134](https://github.com/microsoft/azure-pipelines-tasks/blob/89db84c47a02b94c90303138ca0219d8b8ba80aa/Tasks/DotNetCoreCLIV2/task.json#L128-L134)

Related issue: #5838

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

### PR DESCRIPTION
**Pull request by flcdrg**
Fixes #8352

### CODE REVIEW

**Comment by PRMerger18** [comment]
@flcdrg : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@pulkitaggarwl - can you review?

**Comment by ktoliver** [comment]
@steved0x @pulkitaggarwl - Could you review the proposed update? Thanks.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@steved0x: I'm sorry - only the author of this article, @pulkitaggarwl, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
