### PR TITLE
added a warning for the deletion option for DTL

### PR DESCRIPTION
**Pull request by lalexedwards**
I would like to make this a blocked bold note to help warn customers of this action

### CODE REVIEW

**Comment by Court72** [comment]
@RoopeshNair

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by lalexedwards** [comment]
Hi team, I see this is still open.  Are we able to add this change?

**Comment by Court72** [comment]
@RoopeshNair 

Can you review this proposed update to your article and enter `#sign-off` in a comment if it's approved for merge?
Thanks!

**Comment by steved0x** [comment]
@lalexedwards Thank you for your PR, this will be live today.

#sign-off

**Comment by lalexedwards** [comment]
> @lalexedwards Thank you for your PR, this will be live today.
> 
> #sign-off

Awesome, thank you :)

**Pull request merged**
