### PR TITLE
Update FAQ of conditions

### PR DESCRIPTION
**Pull request by v-avilla**
I added to the documentation an know issue about a conditional step that runs even when a job is canceled

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @v-avilla - Thank you for your contribution. Would you take a moment to sign the CLA? After the CLA is signed, someone will review your changes. Thanks!

**Comment by PRMerger14** [comment]
@v-avilla : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
Thanks @v-avilla! This is a helpful addition.

**Comment by juliakm** [comment]
#sign-off

**Pull request merged**
