### PR TITLE
`publishWebProjects` argument behaviour update

### PR DESCRIPTION
**Pull request by saran-sasidharan**
Reference code : https://github.com/microsoft/azure-pipelines-tasks/blob/3da3b2409ea7bb3f950f99b009ec9df033486c42/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L364

Above default behaviour of the `publishWebProjects` was not covered in the documentation.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@saran-sasidharan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@steved0x: I'm sorry - only the author of this article, @pulkitaggarwl, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
