### PR TITLE
Update the message for pulling down the old Test Plans page.

### PR DESCRIPTION
**Pull request by ShubhamJain1992**
The plan to pull out the old test plan page has been dropped to answer to feedback request in the new test plans page. Hence we need to update the message in the public documentation to keep the user updated.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@ShubhamJain1992 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@ShubhamJain1992 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@ShubhamJain1992 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ravishan-msft** [comment]
#sign-off

**Pull request closed without merging**
