### PR TITLE
Make it  simpler to Create a PAT

### PR DESCRIPTION
**Pull request by focusonmx**
In user settings,  there's already **Personal access tokens** tap. So we just need to select **Personal access tokens** directly.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@focusonmx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by focusonmx** [comment]
I also want to change the  image of second procedure in Create  a PAT.  But I have no idea whether can I change the image on my own. Is it okay to make image and upload it the way I want? or can somebody do it for me?

**Comment by vtbassmatt** [comment]
You can add images yourself. I think there's some kind of requirement to wrap a grey, 1-pixel box around them but don't know the specifics on that. Go ahead and add the image, and one of the reviewers will tell you if there's something more to be done.

**Comment by ktoliver** [comment]
Hi @focusonmx - You can add image files in the PR. 

These are the key rules:

- Screenshots should be enclosed in a gray border that's 1 pixel wide and color #C3C3C3 or RGB (195, 195, 195).
- To highlight details, enclose an item in the screenshot image in a red box that's 3 pixels wide and color #EF1B36 or RGB (239, 27, 54).
- Max file size is 1200 pixels (most images will be quite a bit smaller).
- File names can use only numbers, hyphens (separate words and numbers with hyphens), and lowercase letters.
- Image files can't be merged to root.

Thanks.
-PR review team

**Comment by focusonmx** [comment]
@vtbassmatt  @ktoliver  I added image file. Can this pr be merged?

**Comment by vtbassmatt** [comment]
@focusonmx you've got to do the CLA thing, then I can merge.

**Comment by ktoliver** [comment]
@focusonmx I neglected to mention that the preferred format for a screenshot in this repo is .png format. Would you be able to save the image file as a .png file (lowercase extension)?

**Comment by PRMerger16** [comment]
@focusonmx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by vtbassmatt — APPROVED** [review]

**Comment by ktoliver** [comment]
We'll move forward with the JPG file. Thanks, all.

**Pull request merged**
