### PR TITLE
Add output stream actions to PowerShell task docs

### PR DESCRIPTION
**Pull request by bradselw**
Updating the docs to reflect the changes to the PowerShellV2 task in [this PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15069).

### CODE REVIEW

**Comment by PRMerger13** [comment]
@bradselw : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@bradselw : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bradselw** [comment]
Please do not merge this PR until https://github.com/microsoft/azure-pipelines-tasks/pull/15069 has been merged.

**Comment by PRMerger8** [comment]
@bradselw : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
