### PR TITLE
Fix paths relative to SVN prefix

### PR DESCRIPTION
**Pull request by andersonpimentel**
Added 'svn' prefix on three commands on the migration process. Without it, the process will fail.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@andersonpimentel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@hkamel 

Could you review the proposed changes to your article?

Thanks!

**Comment by ktoliver** [comment]
Hi @chcomley Is this a PR you are able to review? Thanks.

**Comment by chcomley** [comment]
Adding @steved0x

**Comment by PRMerger18** [comment]
@steved0x: I'm sorry - only the author of this article, @hkamel, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by hkamel** [comment]
#sign-off

**Comment by ktoliver** [comment]
Thanks, folks!

**Pull request merged**
