### PR TITLE
Update reference-qa.md

### PR DESCRIPTION
**Pull request by AlexandraRamirezMS**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@AlexandraRamirezMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
