### PR TITLE
Make options for use of PAT much clearer

### PR DESCRIPTION
**Pull request by simonsabin**
Provide list of options for using PAT and the limitations

### CODE REVIEW

**Comment by PRMerger18** [comment]
@simonsabin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by KathrynEE — APPROVED** [review]

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@KathrynEE I made edits for general and Microsoft style. Could you review them before I merge? Thanks.

**Comment by KathrynEE** [comment]
@ktoliver - thanks for making the changes. Go ahead and merge.

**Comment by ktoliver** [comment]
Thank you @KathrynEE

**Pull request merged**
