### PR TITLE
Without explicitly adding an app identity role, the task will fail

### PR DESCRIPTION
**Pull request by kzu**
Make it clear that the `Storage Blob Data Contributor` is a required 
role for successfully using this task

### CODE REVIEW

**Comment by PRMerger20** [comment]
@kzu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@RoopeshNair @steved0x Could you review the proposed update to this article? 

Thank you!

**Comment by kzu** [comment]
This was such a painful/wasteful issue to troubleshoot that it's quite surprising it's taken 4 months and it's still not merged. :(

**Comment by PRMerger18** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
