### PR TITLE
Fix Powershell Repo URLs

### PR DESCRIPTION
**Pull request by magleaso**
URLs refer incorrectly to /v3/index.json and /v3 when they should go to /v2

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@ramiMSFT - IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by magleaso** [comment]
@embetten can you confirm these changes are correct? I get very inconsistent results with adding the repo with /v2. Some people are able to add it, but on my client, it says it's an invalid URL.

**Comment by embetten** [comment]
> @embetten can you confirm these changes are correct? I get very inconsistent results with adding the repo with /v2. Some people are able to add it, but on my client, it says it's an invalid URL.

This looks correct to me. This is the endpoint schema I used to implement and test the powershell gallery support implementation.

**Comment by magleaso** [comment]
@ramiMSFT our eng team signed off, can you take a look?

**Comment by ramiMSFT** [comment]
Thank you @magleaso! I had this set to v2 previously but I had to change it recently based on Alex's feedback here [12293](https://github.com/MicrosoftDocs/azure-devops-docs/issues/12293). Thank you for submitting this PR!

#sign-off

**Pull request merged**
