### PR TITLE
YAML VM Image label => windows-latest = windows-2022

### PR DESCRIPTION
**Pull request by pietergheysens**
Switch from 2019 to 2022

### CODE REVIEW

**Comment by PRMerger13** [comment]
@pietergheysens : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by steved0x** [comment]
@pietergheysens This hasn't fully rolled out yet, I will watch approve this PR when it does (which should be soon). https://github.com/actions/virtual-environments/issues/4856

**Comment by steved0x** [comment]
It has rolled out to all rings, mering this.

#sign-off

**Pull request merged**
