### PR TITLE
Fix rendering of images

### PR DESCRIPTION
**Pull request by pascalberger**
Fixes the rendering of the images which are currently rendered as a code block

### CODE REVIEW

**Comment by PRMerger15** [comment]
@pascalberger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@pascalberger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@pascalberger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chcomley** [comment]
Hi @pascalberger, Thanks for this update. In preview, I still see the images rendered as code block. I believe both images need to be indented with 2 more spaces...

**Comment by PRMerger19** [comment]
@pascalberger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by pascalberger** [comment]
@chcomley I addd two more spaces, but this seems wrong to me. 4 spaces should be fine, like you have in other documents (e.g. [here](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/marketplace/how-to/grant-permissions.md)). 

Is it possible for me to see the preview rendering somewhere? At least on GitHub it renders fine.

**Comment by chcomley** [comment]
#sign-off

**Comment by chcomley** [comment]
Thanks @pascalberger, The preview in GitHub should be fine. I'm not sure what was going on. Thanks very much for your contribution!

**Pull request merged**
