### PR TITLE
Update customize-pipeline.md

### PR DESCRIPTION
**Pull request by Mukesh05**
The second job in the pipeline has a dependency on the first job in the pipeline.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@Mukesh05 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by Mukesh05** [comment]
Please have this reviewed.

**Comment by jborsecnik** [comment]
@vijayma

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@steved0x: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger19** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
