### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by themaroqa**
While deleting a project you need to insert in the box the _Project_ name, not the _Organization_ name.

### CODE REVIEW

**Comment by Court72** [comment]
@chcomley

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by chcomley — APPROVED** [review]
#sign-off

**Comment by Court72** [comment]
@chcomley 

Thanks for reviewing! Note that GitHub doesn't support commands made in the diff review UI. 
In the future, `#sign-off` comments should be made separately in the conversation view, or the PR might get overlooked.

**Comment by chcomley** [comment]
Thanks @Court72

**Pull request merged**
