### PR TITLE
Typo "Azure pipeline"→"Azure Pipelines "

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops&tabs=go-current
https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/go.md
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger4** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @

**Comment by hyoshioka0128** [comment]
@Jak-MS  - Thank you for always helping me.
 #issuecomment-1208321618 is "Invalid command: '#sign-off'."
 What should I do next? Thanks!

**Pull request merged**
