### PR TITLE
Replacing the use of word "master"  with "main" throughout the article.

### PR DESCRIPTION
**Pull request by arnom-ms**
in the graphics I used segoe UI 12 as font for the replacement word

### CODE REVIEW

**Comment by ktoliver** [comment]
cc @mijacobs @steved0x

**Comment by KathrynEE** [comment]
@ktoliver - Can you provide a URL to the staged article? Otherwise, it's hard for me to review this. 
I believe the article that has the changed image files is https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance, however, I don't know what branch to use to see the staged version.

**Comment by ktoliver** [comment]
Hi @KathrynEE - There's no staging in the public repo, but GitHub preview works pretty well for images. In the diff view, right-click **...** and then select **View file**:

image

But here are the preview links, to make it easier:

- https://github.com/MicrosoftDocs/azure-devops-docs/blob/5eb469d07d02784f4ce76b4bb41bddf8b6ab160f/docs/repos/git/media/branching-guidance/featurebranching.png

- https://github.com/MicrosoftDocs/azure-devops-docs/blob/5eb469d07d02784f4ce76b4bb41bddf8b6ab160f/docs/repos/git/media/branching-guidance/releasebranching_main.png

- https://github.com/MicrosoftDocs/azure-devops-docs/blob/023f0c3ea30123c55e2ebd7b38eebeb7d3677686/docs/repos/git/media/branching-guidance/releasebranching_master.png

- https://github.com/MicrosoftDocs/azure-devops-docs/blob/5eb469d07d02784f4ce76b4bb41bddf8b6ab160f/docs/repos/git/media/branching-guidance/releasebranching_release.png

**Comment by ktoliver** [comment]
Thanks!

**Pull request merged**
