### PR TITLE
Update sprint-164-update.md

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
Updated the title to make clear which sprint it is. :-) Much more readable for users to know.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@SebastianSchuetze : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SebastianSchuetze** [comment]
should this be processed or closed?

**Comment by ktoliver** [comment]
@gloridelmorales Could you review this PR from January? Thank you.

**Comment by SebastianSchuetze** [comment]
closing this. It's not too important and is also not being processed.

**Pull request closed without merging**
