### PR TITLE
Version Spec syntax specification

### PR DESCRIPTION
**Pull request by LucaBlackDragon**
Changed the description of the option "Version Spec" according to @steved0x 's answer to this closed issue: https://github.com/MicrosoftDocs/vsts-docs/issues/1393

### CODE REVIEW

**Comment by PRMerger8** [comment]
@LucaBlackDragon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @vijayma - Could you review this pull request? Thanks.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@viyjayma Would you review this pull request? Thanks.

**Comment by ktoliver** [comment]
@steved0x @ramiMSFT @vijayma Would any of you be able to make a call on this submission in the public repository? Thanks.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@steved0x: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
