### PR TITLE
added deprecated/read-only namespaces

### PR DESCRIPTION
**Pull request by pazand**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@pazand : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @pazand - Contributors who work in the Product Manager role should work in the private repository for advanced quality validations and staging (you also can sign off directly in the private repo). To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL. We’ll leave this PR for review in the public repo, but would you make future article updates in the private repo?  Thanks!

**Comment by parsamzand** [comment]
@ktoliver thanks for letting me know! Will do next time.

**Comment by ktoliver** [comment]
Thanks @parsamzand 

@KathrynEE Could you review the pull request? Thanks.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
