### PR TITLE
Remove docs related to deprecated deploy-to-azure vs code extension

### PR DESCRIPTION
**Pull request by bishal-pdMSFT**
The VS Code extension [Deploy to Azure](https://marketplace.visualstudio.com/items?itemName=ms-vscode-deploy-azure.azure-deploy) has been deprecated. This PR removes the doc related to it.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@bishal-pdMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KathrynEE** [comment]
@[bishal-pdMSFT](https://github.com/bishal-pdMSFT), @juliakm - I'm wondering if this content should be archived instead of just deleted. Unfortunately, we are having some issues with our archive repo, but I can take an action to archive the current copy once that get's addressed. 

Also - we should add a redirect link to the .openpublishing.redirection.json file for the deleted file. If there is no article to redirect it to or blog post, then at a minimum it should be redirected to the github issue deprecation notice URL: https://github.com/microsoft/vscode-deploy-azure/issues/239.

**Comment by PRMerger4** [comment]
@bishal-pdMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bishal-pdMSFT** [comment]
>Also - we should add a redirect link to the .openpublishing.redirection.json file for the deleted file. If there is no article to redirect it to or blog post, then at a minimum it should be redirected to the github issue deprecation notice URL: https://github.com/microsoft/vscode-deploy-azure/issues/239.

@KathrynEE I made the change for redirect url. But I am not sure if that is correct as all other urls in this file are using relative paths. Is this going to cause problem? Please feel free to update the PR with right url.

**Review by KathrynEE — APPROVED** [review]

**Review by azooinmyluggage — APPROVED** [review]
LGTM

**Comment by Court72** [comment]
@KathrynEE 
@juliakm 
@pulkitaggarwl 

These changes need to be made in the private repo for validation checks.
Could you pull the commits into a new PR in the private repo?

Thanks.

**Comment by KathrynEE** [comment]
@bishal-pdMSFT - I hadn't noticed that this was in the public repo and not the private repo. 
Adding @steved0x - Steve is there an easy way to get this incorporated into the public repo? It's mostly a delete on an article, update redirect, and remove cross links - so there isn't much that needs to be reviewed editorially.

**Comment by bishal-pdMSFT** [comment]
I am not sure which private repo is being talked about here. Please point me and I will raise a PR there. I assume private to public replication will happen automatically?

**Pull request closed without merging**
