### PR TITLE
Fixed: Code sample still uses preview version of REST API

### LINKED ISSUE #10679: Clarification needed: Should the API sample still use API preview version?
The sample code uses a preview version of the API. Is this still current, or does this need updating?

``` csharp
?api-version=4.1-preview.1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915c7aa9-0969-912b-bbc4-a2b0bf9b1533
* Version Independent ID: 6a97a5e8-8397-be98-5528-70d20e8fbed8
* Content: [Use Azure Functions to create custom branch policy - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server-with-azure-functions?toc=%2fazure%2fdevops%2fmarketplace-extensibility%2ftoc.json&bc=%2fazure%2fdevops%2fmarketplace-extensibility%2fbreadcrumb%2ftoc.json&view=azure-devops&WT.mc_id=DOP-MVP-21138)
* Content Source: [docs/repos/git/create-pr-status-server-with-azure-functions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/create-pr-status-server-with-azure-functions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

### PR DESCRIPTION
**Pull request by NenoLoje**
This PR fixes #10679

### CODE REVIEW

**Comment by PRMerger7** [comment]
@NenoLoje : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@juliakm: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by NenoLoje** [comment]
> 
> 
> @juliakm: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. 

@vijayma - please help and approve. :-)

**Pull request merged**
