### PR TITLE
Note ArtifactName can't contain + % { }

### PR DESCRIPTION
**Pull request by Codym48**
Related to
- https://github.com/microsoft/azure-pipelines-tasks/issues/16697
- https://github.com/microsoft/azure-pipelines-tasks/pull/16730

### CODE REVIEW

**Comment by Jak-MS** [comment]
@vijayma - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by ramiMSFT — APPROVED** [review]

**Comment by ramiMSFT** [comment]
@Codym48 Thank you for your contribution!

#sign-off

**Comment by jborsecnik** [comment]
@vijayma, ok to merge?

**Comment by steved0x** [comment]
@Codym48 Thank you for your PR. The task reference has moved, and I have added your changes to the new location. You can see them by going to the new task and scrolling to the `ArtifactName` input:

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1?view=azure-pipelines#inputs

image

**Comment by Codym48** [comment]
Thank you, @steved0x! Have the task definitions moved, too? Consider cherry-picking and implementing https://github.com/microsoft/azure-pipelines-tasks/pull/16730, too?

**Pull request closed without merging**
