### PR TITLE
Update deployment-jobs.md

### PR DESCRIPTION
**Pull request by jossgc**
About reserved words.

### CODE REVIEW

**Comment by ManuelGalindo** [comment]
great Joss lets wait for the review

**Comment by PRMerger9** [comment]
@jossgc : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
#sign-off

@jossgc Thanks for your contribution! Do you have examples of keywords? Would `rolling` be one? Approving this PR but that might be something helpful to add. Thanks again.

**Comment by jossgc** [comment]
> #sign-off
> 
> @jossgc Thanks for your contribution! Do you have examples of keywords? Would `rolling` be one? Approving this PR but that might be something helpful to add. Thanks again.

Thank you! Yes, one particular example: `Deploy`.

**Pull request merged**
