### PR TITLE
Adding clarification to views note

### PR DESCRIPTION
**Pull request by ryangurn**
This is unclear because the default view can be changed in AzDo but not really at runtime, only on a global level. I am open to any feedback on wording since the original text is causing quite a bit of confusion.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@ramiMSFT 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ryangurn** [comment]
@Jak-MS, do you have any recommendations on the wording or is that mostly @ramiMSFT who would provide that PR feedback?

**Comment by Jak-MS** [comment]
@ryangurn - @ramiMSFT will respond as time permits to review your suggested changes. Thanks!

**Comment by ramiMSFT** [comment]
@ryangurn Thank you for your contribution. However, this is not accurate. Changing the default view (to "Release" for example) does not enable direct publishing to that view. Packages can only be published to the base feed, where they will be available in the "Local" view.

**Pull request closed without merging**
