### PR TITLE
Added example of coverage settings

### PR DESCRIPTION
**Pull request by lkurzyniec**
Added simple configuration

```yaml
coverage:
  status:           #Code coverage status will be posted to pull requests based on targets defined below.
    comments: on    #Off by default. When on, details about coverage for each file changed will be posted as a pull request comment. 
    diff:           #diff coverage is code coverage only for the lines changed in a pull request.
      target: 60%   #set this to a desired %. Default is 70%
```

### CODE REVIEW

**Comment by PRMerger10** [comment]
@lkurzyniec : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by lkurzyniec** [comment]
Any info here?

**Comment by PRMerger8** [comment]
@juliakm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
#sign-off

Works for me with slight changes. The code matches [this in the samples repo]
(https://github.com/MicrosoftDocs/codecoverage-yaml-samples/blob/master/EnableCoverageDetailComments/azurepipelines-coverage.yml).

**Comment by PRMerger8** [comment]
@juliakm: I'm sorry - only the author of this article, @shashban, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
