### PR TITLE
Replace email with a link to form for free tier request

### PR DESCRIPTION
**Pull request by alexander-smolyakov**
**Description**:
Since Azure DevOps is already directing customers to fill out a Microsoft Form to request free parallelism, we also should update the related docs as well. 

**Changes**:
- `azpipelines-freetier@microsoft.com` replaced with the link to the form: `https://aka.ms/azpipelines-parallelism-request`

### CODE REVIEW

**Comment by PRMerger9** [comment]
@alexander-smolyakov : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by anatolybolshakov — APPROVED** [review]

**Comment by alexander-smolyakov** [comment]
@vijayma @stephenmichaelf Could you please take a look at these changes?

**Review by stephenmichaelf — APPROVED** [review]
Looks good to me. Let's get @vijayma to approve too.

**Review by vijayma — APPROVED** [review]

**Comment by vijayma** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@vijayma: I'm sorry - only the author of this article, @steved0x, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by alexander-smolyakov** [comment]
@steved0x Could you please review these changes?

**Comment by PRMerger18** [comment]
@alexander-smolyakov: I'm sorry - only the author of this article, @steved0x, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
