### PR TITLE
Add deployment variable syntax examples, notes

### PR DESCRIPTION
**Pull request by KyMidd**
Hey team! 

Thanks for building this great product. I got stuck for a while on calling variables from deployment pipelines. The syntax used for variables vs conditionals is different (!?), so I wanted to document it, add some notes for folks to find that information, and make one small bug-fix in an example that isn't correct. 

Please feel free to make edits, would love to get this information added so others can save some time. 

Thanks!
kyler

### CODE REVIEW

**Comment by PRMerger16** [comment]
@KyMidd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KyMidd** [comment]
Hey team, is it possible to get this merged? I imagine there will be source drift if we wait too long.

**Comment by ktoliver** [comment]
@juliakm Could you review the proposed updates to your articles? Thanks.

**Comment by juliakm** [comment]
#sign-off

Thanks @KyMidd!

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
