### PR TITLE
Updated FAQ

### PR DESCRIPTION
**Pull request by gimmi**
The stepd for building multiarch Docker images changed a bit

### CODE REVIEW

**Comment by PRMerger9** [comment]
@gimmi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@juliakm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @azooinmyluggage

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@juliakm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @azooinmyluggage

**Comment by PRMerger13** [comment]
@juliakm: I'm sorry - only the author of this article, @azooinmyluggage, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change. @azooinmyluggage

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change. @azooinmyluggage

**Pull request merged**
