### PR TITLE
Update Call Rest API Client - TFS 

### PR DESCRIPTION
**Pull request by DreyIMM**
This commit has goal update version calle HttpClient. 
For this page:
https://learn.microsoft.com/en-us/azure/devops/integrate/how-to/call-rest-api?toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&view=azure-devops-2020&source=docs

### CODE REVIEW

**Comment by DreyIMM** [comment]
@microsoft-github-policy-service agree [company="{DSY}"]

**Comment by DreyIMM** [comment]
@microsoft-github-policy-service agree company="Developer Solution For You"

**Comment by Court72** [comment]
@dreyimm - Thanks for your pull request. A member of the content team will review it.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by steved0x** [comment]
@DreyIMM Thank you for this update. Our stale bot automation accidentally closed this PR before we had a chance to review it.

From the notes in the PR description, I believe that you want to make an update to the following article: https://learn.microsoft.com/en-us/azure/devops/integrate/how-to/call-rest-api?view=azure-devops

The source for that article in GitHub is here:
https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/how-to/call-rest-api.md

Can you go there and make your updates in a new PR that updates that article? Your current PR is adding a new file in the wrong location for articles, so I am closing it, but if you create an update to the article using the link above, we will review and and get it added. Thank you.

**Pull request closed without merging**
