### PR TITLE
adding note on gatekeeper alerts

### PR DESCRIPTION
**Pull request by cicorias**
on macOS gatekeeper protection presents
a dialog box for every single assembly loaded
when laucnhing config.sh - by issueing the
xattr command to clear the special attribute
on the downloaded archive this prevents
that constant dialog. see https://github.com/microsoft/azure-pipelines-agent/issues/2457

and https://github.com/microsoft/azure-pipelines-agent/issues/2457#issuecomment-548661284

### CODE REVIEW

**Comment by PRMerger15** [comment]
@cicorias : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@cicorias : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
