### PR TITLE
Update azure-devops-auditing.md

### PR DESCRIPTION
**Pull request by angelwong**
Updating list to include new audit event types: User and Token/Authentication

### CODE REVIEW

**Comment by PRMerger19** [comment]
@angelwong : Thanks for your contribution! The author(s) have been notified to review your proposed change. @roferg

**Comment by ktoliver** [comment]
Hi @chcomley - @roferg is listed in the metadata `author` attribute, but they aren't in the Microsoft Docs organization, so I can't assign the pull request to them. I'll assign it to you instead, OK? Thanks.

**Comment by ktoliver** [comment]
Hi @angelwong - If you're internal to Microsoft and a PM, per the internal CG, you should work in the private repo. Let me know if you need information about working in the private repo; I can send it to you in email. Thanks.

**Review by chcomley — APPROVED** [review]

**Comment by ktoliver** [comment]
@chcomley Thanks for your review.

When the pull request is set to **Ready for review**, we'll check for updates and either merge or check in again with the content team. Thanks.

**Pull request merged**
