### PR TITLE
Updates documentation

### PR DESCRIPTION
**Pull request by eliaslopezgt**
Fixes error in documentation that specifies a wrong value for `deploymentMode`.
The correct value should be `Validation` not `Validate`.
Using the incorrect value results in the Template being deployed. See https://github.com/microsoft/azure-pipelines-tasks/blob/7667d6eb7ba031ce3ea30c51d42c1f5fa186f089/Tasks/AzureResourceManagerTemplateDeploymentV3/operations/DeploymentScopeBase.ts#L50

### CODE REVIEW

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
