### PR TITLE
Update allow-list-ip-url.md

### PR DESCRIPTION
**Pull request by Jominana**
Added a bit more details on the  CDN section and .cn domains.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@Jominana : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chcomley — APPROVED** [review]

**Comment by chcomley** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Microsoft has moved from using "whitelist" to using "allow list". Thanks!

**Pull request merged**
