### PR TITLE
Anaconda environments changes

### PR DESCRIPTION
**Pull request by trallard**
This PR adds the following changes for conda environments:
- Ensure we use the conda Python
- Add note about adding relevant conda channels

### CODE REVIEW

**Comment by PRMerger14** [comment]
@trallard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@vijayma Could you review this pull request from December? Thanks.

**Comment by ktoliver** [comment]
@vijayma @chcomley - Could you review the proposed article update from December? 

Thank you

**Comment by ktoliver** [comment]
@chcomley Thank you

**Pull request merged**
