### PR TITLE
Update workspace-command.md

### PR DESCRIPTION
**Pull request by AlexandraRamirezMS**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@steved0x or @JKirsch1 - can you review? 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by JKirsch1 — COMMENTED** [review]
Thanks for this valuable addition to the article! I ran the first two commands and verified that they retrieve the ID of the workspace owner and the name of the workspace. I didn't run the third command (the one that actually deletes the workspace), because I think something's missing from the syntax, and I didn't want to unintentionally delete more workspaces than necessary.

Currently the third command is this line:

tf workspace /delete /collection:`<team-project-collection-url>` /owner:"OwnerID"

I think you need to specify the workspace name somewhere in that command. Otherwise, it doesn't make sense to retrieve that name first. The correct syntax might be something like this line, but I haven't verified it:

tf workspace /delete <workspace-name>;<workspace-owner> /collection:<team-project-collection-url>

The only changes I'd request to this PR are:

1. Verify the version of the delete command that includes the workspace name.
2. Make the following minor edits to align language and formatting with style guide conventions.

When you delete a workspace, you need to provide values for the `<workspace-owner>` and `<workspace-name>` parameters.

You can use the `workspaces` command to retrieve those values. For more information, see [Workspaces command](workspaces-command.md).

To find the `<workspace-owner>` value, run the following command:

```
c:\projects>tf workspaces /computer:* /owner:* /collection:`<team-project-collection-url>` /format:xml
```

To find the `<workspace-name>` value, use the `ownerid` value from the previous command's output as the `<workspace-owner>` value. That value has the format of an Azure Active Directory (Azure AD) object ID followed by a backslash and a user principal name. Use the entire value. Then run the following command:

```
c:\projects>tf workspaces /owner:<workspace-owner> /computer:* /collection:`<team-project-collection-url>`
```

To delete the workspace, run the following command:

```
c:\projects>tf workspace /delete <workspace-name>;<workspace-owner> /collection:<team-project-collection-url>
```

**Comment by AlexandraRamirezMS** [comment]
New PR with the required changes
Update workspace-command.md by AlexandraRamirezMS * Pull Request #13509 * MicrosoftDocs/azure-devops-docs (github.com)<https://github.com/MicrosoftDocs/azure-devops-docs/pull/13509>


Best Regards,

Alexandra Ramirez
Azure Devops Services
Partner Technical Advisor

Customer Service and Support
Office: +52 55 5267 2144
***@***.******@***.***>
Working hours: 08.00 - 17.00 CST

[Graphical user interface  Description automatically generated with low confidence]We are always interested to hear your feedback. Please feel free to reach my manager regarding the level of service you have received, at Chetan Rao < ***@***.******@***.***> >

**Comment by steved0x** [comment]
Closing due to new PR https://github.com/MicrosoftDocs/azure-devops-docs/pull/13509

**Pull request closed without merging**
