### PR TITLE
Added AKS and ACR integration also common error and how to fixit

### PR DESCRIPTION
**Pull request by ManuelGalindo**
We got several cases asking the same scenario, how to and how to fix the CR on Windows, added the guides.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@ManuelGalindo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @steved0x Could you review the proposed update to your article? Thanks.

**Review by steved0x — APPROVED** [review]

**Comment by PRMerger16** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
