### PR TITLE
Added guide when tfx missing

### PR DESCRIPTION
**Pull request by cpoDesign**
Added information on, how to get tfx command installed, in order to generate the extension

### CODE REVIEW

**Comment by PRMerger9** [comment]
@cpoDesign : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@willsmythe Could you review this pull request? Thanks.

**Comment by cpoDesign** [comment]
@willsmythe @ktoliver Let me know if you need anything else

**Comment by ktoliver** [comment]
@willsmythe Will, could you review this PR from October 2019?

@aaronhallberg

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@mijacobs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mijacobs** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@mijacobs: I'm sorry - only the author of this article, @apawast, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Thanks @mijacobs; merging now.

**Pull request merged**
