### PR TITLE
Update security-best-practices.md

### PR DESCRIPTION
**Pull request by azarboon**
Implementing principle of least privilege in the context of CI/CD, is a bit nuanced. Currently, the page just give a generic and not-very-practical advice. I've added a Note to explain the nuances of point.

### CODE REVIEW

**Comment by Court72** [comment]
@chcomley

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by chcomley** [comment]
Thank you @azarboon!

**Comment by azarboon** [comment]
> Thank you @azarboon!

Your welcome. And thanks for the edit. Please sign this off so it can be merged.

**Comment by chcomley** [comment]
#sign-off

**Pull request merged**
