### PR TITLE
MS Teams and Azure Boards Integration 

### PR DESCRIPTION
**Pull request by jodachecallan**
- Added Additional Method for MS Teams and Azure Boards Integration

### CODE REVIEW

**Comment by PRMerger13** [comment]
@jodachecallan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@divais - Hi, would you review the proposed update to your article? Thanks.

**Comment by steved0x** [comment]
@KathrynEE Could you review for Boards?

**Comment by KathrynEE** [comment]
@jodachecallan - I'm closing this PR without completing it as I can't confirm the changes you've introduced.

**Pull request closed without merging**
