### PR TITLE
Correct QnA enablement key

### PR DESCRIPTION
**Pull request by shaaradmsft**
Creating this PR to correct the extension manifest key name from `enableqna` to `enablemarketplaceqna`.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@shaaradmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chcomley — APPROVED** [review]

**Comment by shaaradmsft** [comment]
@chcomley how do we go about merging this PR? I don't have the merge rights here, is there a validation that's pending? Can you please guide?

**Comment by chcomley** [comment]
#sign-off

**Comment by chcomley** [comment]
Hi @shaaradmsft, needed a "#sign-off" and I've done that. It's now be reviewed and merged by the review team. Thank you for your updates!

**Comment by chcomley** [comment]
#sign-off

**Comment by chcomley** [comment]
@ktoliver This update isn't live. I assume it's due to the recent outage, but can this be confirmed please? Will this automatically be published once it's all back up and running? Thanks!

**Comment by ktoliver** [comment]
@chcomley The answers are yes and yes. I don’t have an ETA for the next publish cycle.

**Pull request merged**
