### PR TITLE
Update about-azure-devops-services-tfs.md

### PR DESCRIPTION
**Pull request by irtizamahmud**
Test pull request for content developer role

@j-martens

### CODE REVIEW

**Comment by PRMerger20** [comment]
@irtizamahmud : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
Hi @irtizamahmud - This looks like a test PR that can't be merged in. Would you like us to close it? Thanks!

cc @chcomley

**Comment by irtizamahmud** [comment]
Yes please.

Thanks
Irtiza

**Pull request closed without merging**
