### PR TITLE
Updating a note the deleting project wiki is not supported

### PR DESCRIPTION
**Pull request by amitkumariiit**
Updating a note the deleting project wiki is not supported

### CODE REVIEW

**Comment by PRMerger19** [comment]
@amitkumariiit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chcomley — APPROVED** [review]

**Comment by chcomley** [comment]
#sign-off

**Comment by amitkumariiit** [comment]
@chcomley  can you merge this PR. I seems not to have the permission to do so.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
