### PR TITLE
Update approvals.md

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
added new places for checks see:

https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-187-update#permissions-and-checks-on-variable-groups-and-secure-files

and

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/repository-resource?view=azure-devops

### CODE REVIEW

**Comment by PRMerger8** [comment]
@SebastianSchuetze : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SebastianSchuetze** [comment]
Any update on the review?

**Comment by ktoliver** [comment]
@steved0x @vijayma Could you take a look? Thanks.

**Review by vijayma — APPROVED** [review]

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks, all.

**Pull request merged**
