### PR TITLE
update vstests.md minor grammar

### PR DESCRIPTION
**Pull request by dylan-apera**
Changes to grammar for document to make sense

### CODE REVIEW

**Comment by PRMerger14** [comment]
@dylan-apera : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger14** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @shashban

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger6** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @shashban

**Pull request merged**
