### PR TITLE
Added known issues section in the document for publish code coverage results task

### PR DESCRIPTION
**Pull request by ganesp**
Added known issues section in the document for publish code coverage results task

### CODE REVIEW

**Comment by PRMerger13** [comment]
@ganesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
In this repository, actual image files must be added to the repo in order to reference the images in an MD file. We can't reference or include images that are hosted outside the repo in an MD file.

**Comment by PRMerger14** [comment]
@ganesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ganesp** [comment]
> In this repository, actual image files must be added to the repo in order to reference the images in an MD file. We can't reference or include images that are hosted outside the repo in an MD file.

@ktoliver I have addressed this comment. Please review.

**Comment by PRMerger14** [comment]
@ganesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ganesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@ganesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ganesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@ganesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ganesp** [comment]
@aaronhallberg 
Can you please approve this PR? This is to document a known issue with the publish code coverage results task.

//cc: @nadesu

**Comment by nadesu** [comment]
@vijayma can you help review the PR?

**Review by vijayma — APPROVED** [review]

**Comment by vijayma** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@vijayma: I'm sorry - only the author of this article, @shashban, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@ganesp Before we merge, would you be able to make a change to both image files? The standard in Microsoft Docs content is to use a red outline to emphasize or highlight items in a screenshot. Here's an example:

image

To create a red outline, use 3-pixel width with red color #EF1B36 or RGB (239, 27, 54). Vertically center the element or text that you want to outline in red.

Could you replace the yellow highlighting in both images with a red outline?

Also, images should be no more than 1200 pixels in any dimension.

Alternatively, we could merge this as it is and we'd follow up with a PR to replace the images according to these standards (red outline for highlighting and max 1200 pixels).

**Comment by PRMerger15** [comment]
@ganesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@ganesp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ganesp** [comment]
@ktoliver I have tried to incorporate your feedback on the images. Please check.

//cc: @nadesu

**Comment by ktoliver** [comment]
@ganesp Thank you. Can I request one more change? Your name was added in the latest version of publish-code-coverage-result-build-summary.png. Could you remove the text and icon? Or, you can delete the entire line (I'd probably do the latter).

image

 Then, we'll merge the pull request. Thanks!

**Comment by ganesp** [comment]
> @ganesp Thank you. Can I request one more change? Your name was added in the latest version of publish-code-coverage-result-build-summary.png. Could you remove the text and icon? Or, you can delete the entire line (I'd probably do the latter).
> 
> image
> 
> Then, we'll merge the pull request. Thanks!

@ktoliver Done. Removed my name.

**Comment by ktoliver** [comment]
@ganesp Thank you! Merging.

**Pull request merged**
