### PR TITLE
Update rename-project.md

### PR DESCRIPTION
**Pull request by AlexandraRamirezMS**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@AlexandraRamirezMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@chcomley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chcomley** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
(The Microsoft Writing Style Guide says to avoid using "foobar".)

**Pull request merged**
