### PR TITLE
Correct App Service Plan Windows vs Linux

### PR DESCRIPTION
**Pull request by ruandersMSFT**
Contains copy and paste error.  Windows section copied from Linux, states creation of Linux, but should say Windows.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@ruandersMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
@juliakm for review. Thanks!

**Comment by juliakm** [comment]
Thank you @ruandersMSFT! 

#sign-off

**Pull request merged**
