### PR TITLE
Adding clarifying note on feeds

### PR DESCRIPTION
**Pull request by herenhuang**
I'm onboarding onto the team + adding clarifying info on certain concepts that I think may help others

### CODE REVIEW

**Comment by PRMerger6** [comment]
@herenhuang : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @herenhuang 

PMs and content developers should work in the private repository as described in [Should I work in a private or a public repo?](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=master) The private repo is at https://github.com/MicrosoftDocs/vsts-docs-pr.

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-local?branch=master).

In the private repos, your content gets the benefit of quality validation, and you can verify it on staging before publishing. Some PRs that have fewer updates might qualify for auto-merge.

(If you want a member of the content team to review your updates in the private repo before merging, you can request a review or at-mention them in a comment before you sign off. See [GitHub for content reviews](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-reviews?branch=master).)

We can keep this PR here in the public repo for review, but would you create future pull requests in the private repo? Thank you!

**Comment by herenhuang** [comment]
Sounds good! I'm assuming if I want to make small scale changes I can just make edits in the private repo vs setting up the whole repo locally? @ramiMSFT - is there anything I need to do here still?

**Comment by ktoliver** [comment]
Hi @herenhuang - Yes. See the note in this section: https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-edit-article?branch=master#update-an-existing-article

Thanks.

**Comment by ktoliver** [comment]
Hi @ramiMSFT - Could you review the proposed update to your article? Thanks.

**Comment by ramiMSFT** [comment]
> **EDITED**
> 
> Hi @herenhuang Helen Huang FTE
> 
> PMs and content developers should work in the private repository as described in [Should I work in a private or a public repo?](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=master) The private repo is at **https://github.com/MicrosoftDocs/azure-devops-docs-pr**.
> 
> If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-local?branch=master).
> 
> In the private repos, your content gets the benefit of quality validation, and you can verify it on staging before publishing. Some PRs that have fewer updates might qualify for auto-merge.
> 
> (If you want a member of the content team to review your updates in the private repo before merging, you can request a review or at-mention them in a comment before you sign off. See [GitHub for content reviews](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-reviews?branch=master).)
> 
> We can keep this PR here in the public repo for review, but would you create future pull requests in the private repo? Thank you!

Closing this PR to the public repo.

**Pull request closed without merging**
