### PR TITLE
Update FAQ in pipeline-artifacts.md

### PR DESCRIPTION
**Pull request by ericmutta**
The opening sentence of this document says:

> You can also publish your artifact to a file share...

But towards the end, in the FAQ section, we have this:

> **Q: Do you support publishing artifacts to a shared folder?**
> A: Not currently, but this feature is planned.

It appears that publishing to a shared folder was implemented at some point but the FAQ was not updated. I have now removed the question because the docs say directly that publishing to a shared folder is supported. This change is valid assuming that "file share" and "shared folder" refer to the same thing (which I think they do!).

### CODE REVIEW

**Comment by Court72** [comment]
@ramiMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ericmutta** [comment]
It's been two months...any updates on this?

**Comment by ericmutta** [comment]
Closing since reviewer is non-responsive 😢

**Comment by ericmutta** [comment]
Hello @WilliamAntonRohm another month has passed and still no response from @ramiMSFT...could it be that he is simply not seeing these messages?

**Review by ramiMSFT — APPROVED** [review]

**Comment by ramiMSFT** [comment]
@ericmutta Thanks for your contribution! Not sure what happened to the notifications. Thanks for catching this.

#sign-off

**Comment by ericmutta** [comment]
Thanks @ramiMSFT for following up, it's good to know you are still alive and kicking, we got worried for a while there given the extended silence 😄

**Pull request merged**
