### PR TITLE
Update pipeline caching docs to include task example for Golang

### PR DESCRIPTION
**Pull request by geetanjaliy**
Updating documentation to include directions to enable support for pipeline caching for Golang.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@geetanjaliy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by geetanjaliy** [comment]
Hi team, I have not received any email or input on the necessary changes required for this pull request. Can I please know what's the issue with this merge request?

**Comment by ktoliver** [comment]
@steved0x and @ramiMSFT - Could you review the proposed update to this pipelines article? Thanks.

**Comment by ktoliver** [comment]
Hi @geetanjaliy - Thank you for your content update submission. The pull request has been assigned to the content team for review. It's likely that holiday closures have delayed responses. Thanks.

**Comment by geetanjaliy** [comment]
Hi team,I have not received any email or input on the necessary changes required for this pull request. Can I please know what's the issue with this merge request?

**Comment by ktoliver** [comment]
> Hi team,I have not received any email or input on the necessary changes required for this pull request. Can I please know what's the issue with this merge request?

Hi @ramiMSFT @steved0x @KathrynEE - Could you review this community contribution to a pipelines article? Thanks.

**Comment by PRMerger17** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ramiMSFT — APPROVED** [review]

**Pull request merged**
