### PR TITLE
Update docker.md

### PR DESCRIPTION
**Pull request by Frettarix**
Missing an '\\' to continue the RUN command.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@Frettarix : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
@Frettarix Thank you for fixing this!

**Comment by steved0x** [comment]
#sign-off

**Comment by steved0x** [comment]
I just realized several folks made this correction and it has already been merged into the private repo so I am closing this. Thank you!

**Pull request closed without merging**
