### PR TITLE
Update run-number.md

### PR DESCRIPTION
**Pull request by jtpetty**
Updating to be explicit about a limitation using expressions to set the build number

### CODE REVIEW

**Comment by PRMerger16** [comment]
@jtpetty : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by damccorm — APPROVED** [review]

**Comment by ktoliver** [comment]
Pull requests in this repository need to be signed off by a member of the content team or the product management team to merge. 

@juliakm Could you take a look? Thanks.

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks, all.

**Pull request merged**
