### PR TITLE
Added Azure CLI/ Bash & REST API Task variant

### PR DESCRIPTION
**Pull request by BKers**
New languages added for retaining pipelines.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@BKers : Thanks for your contribution! The author(s) have been notified to review your proposed change. @moswald

**Comment by Jak-MS** [comment]
#assign: @moswald 

@moswald 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger16** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: moswald

**Comment by Jak-MS** [comment]
@mijacobs - I can't assign the listed author. can you review?

Note that because tabbed content is being added or changed, the commits in this PR will need to be moved or resubmitted via the private repo.

**Comment by BKers** [comment]
> @mijacobs - I can't assign the listed author. can you review?
> 
> Note that because tabbed content is being added or changed, the commits in this PR will need to be moved or resubmitted via the private repo.

Any updates on review of the PR?

**Comment by steved0x** [comment]
#sign-off

**Review by moswald — APPROVED** [review]

**Comment by jborsecnik** [comment]
@moswald, can you move these changes to the private repo so they can be viewed on staging? Do you need assistance? Thanks.

**Comment by moswald** [comment]
Yeah, I don't know what that means. 😄

**Comment by mijacobs** [comment]
@Julia ***@***.***>, could you help Matt submit this PR to the private repo, since Rami is out?

Thanks,
Mike

**Comment by mijacobs** [comment]
Hi Matt,

I created a new PR for you to review in the private repo: https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5013

Here's the instructions in the Contributor's Guide article for next time: https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=main#move-public-changes-by-pulling-to-the-private-repo

Best,
Julia
________________________________
From: Mike Jacobs ***@***.***>
Sent: Wednesday, September 7, 2022 6:40 PM
To: MicrosoftDocs/azure-devops-docs ***@***.***>; MicrosoftDocs/azure-devops-docs ***@***.***>; Julia Kulla-Mader ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/azure-devops-docs] Added Azure CLI/ Bash & REST API Task variant (PR #12554)


@Julia ***@***.***>, could you help Matt submit this PR to the private repo, since Rami is out?



Thanks,

Mike

**Comment by moswald** [comment]
I didn't create this PR first time, though. 🤷

Can we remove me from the required-reviewers list? I don't work on this area of AzDevOps anymore and someone from the current Pipelines team should really be reviewing these.

**Pull request closed without merging**
