### PR TITLE
added deploy.sh

### PR DESCRIPTION
**Pull request by abhishek0220**
There is no sample deploy.sh not even in repo refered which creates issue when creating one, so added the link for the same

### CODE REVIEW

**Comment by PRMerger6** [comment]
@abhishek0220 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@steved0x Could you review this pipelines pull request? Thanks.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
