### PR TITLE
update(migration-overview): New Version Support

### PR DESCRIPTION
**Pull request by cogswell**
- Add that we support Azure DevOps Server 2020.0.1 now
- Add note that we expect to remove support for 2019.1.1
- Uncomment Preview Features section since Analytics is still in preview
- DataMigrationTool references the Preview Features section by way of https://aka.ms/AzureDevOpsImportPreviewFeatures

### CODE REVIEW

**Comment by PRMerger12** [comment]
@cogswell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by KathrynEE — APPROVED** [review]

**Comment by KathrynEE** [comment]
@cogswell - Approving this for publishing. In the future, it's better if you make updates to the azure-devops-docs-pr repo. Thanks, Kathryn

**Comment by C-Ross** [comment]
Thanks @KathrynEE is there something I can read to help understand the difference in the *-docs and *-docs-pr repos?

**Comment by KathrynEE** [comment]
@C-Ross - The main difference is that azure-devops-docs repo is the public repo for customers to provide feedback on a doc. azure-devops-docs-pr is the repo where we author new content and updates to existing content. It is setup to go through a review process with editors to ensure quality. Anyone who works for Microsoft is asked to work in the private repos (-pr).

**Comment by cogswell** [comment]
Thanks @KathrynEE Sorry, wasn't familiar with the process.

**Pull request merged**
