### PR TITLE
Typo in customRegistry argument

### PR DESCRIPTION
**Pull request by BobBuildingCode**
Argument is customRegistry, not customRegistries

### CODE REVIEW

**Comment by PRMerger14** [comment]
@BobBuildingCode : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@steved0x: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger-2** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
