### PR TITLE
Date/time variable examples in Azure Pipeline

### PR DESCRIPTION
**Pull request by mahi072**
Provided four different methods for adding date/time variables using detailed explanation for each method. These provided examples can be modified and used in different scenario as per requirement.

### CODE REVIEW

**Comment by Court72** [comment]
@mahi072 

Thank you for your contribution. Would you take a moment to sign the [Contributor License Agreement (CLA)](https://github.com/MicrosoftDocs/azure-devops-docs/pull/12930#issuecomment-1329843490)? After the CLA is signed, someone can review your pull request. Thanks!

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by mahi072** [comment]
@microsoft-github-policy-service agree [company="{}"]

I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

**Comment by mahi072** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@shashban

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Comment by mahi072** [comment]
Hi @shashban, please review the proposed changes.

**Comment by steved0x** [comment]
#assign juliakm
#assign ramimsft

This looks like it might be good to be added in variables (@juliakm), but in this PR it looks like it is in the context of a release (@ramiMSFT) Rami could you review this PR?

**Comment by ramiMSFT** [comment]
@mahi072 Thanks for your contribution! However this content is out of place. Can you start a PR to the following article instead: [Define variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
GitHub: https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/variables.md

**Pull request closed without merging**
