### PR TITLE
Update use-ssh-keys-to-authenticate.md

### PR DESCRIPTION
**Pull request by JWStarkie**
Adding additional guidance on steps that can be taken to copy the public key value to the clipboard, for uploading to ADO.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@JWStarkie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger5** [comment]
@steved0x: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
