### PR TITLE
Update deployment-jobs.md

### PR DESCRIPTION
**Pull request by arkoppan**
1.Corrected the statement for example where the output variable is set in a non-deployment job.
2. Added the example to reference an output variable from a deployment job.
3. Made some corrections to variable names in other examples.
4. Corrected the reference example when using resource name.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@juliakm 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by juliakm** [comment]
@arkoppan Thanks for your edits!

#sign-off

**Comment by Jak-MS** [comment]
@arkoppan @juliakm - merging this PR https://github.com/MicrosoftDocs/azure-devops-docs/pull/14142  has seemingly caused a merge conflict ... can you address/fix and then tag me to review again? thanks.

**Comment by Jak-MS** [comment]
#hold-off

**Comment by hunyu** [comment]
Do we have an update on this @arkoppan @juliakm?

**Comment by arkoppan** [comment]
> @arkoppan @juliakm - merging this PR #14142 has seemingly caused a merge conflict ... can you address/fix and then tag me to review again? thanks.

@Jak-MS The changes from this PR [14142 ](https://github.com/MicrosoftDocs/azure-devops-docs/pull/14142) can be overridden with the changes suggested in this PR 14141 (as the variable vmsfortesting is defined in the environment on line 478.


@hunyu @juliakm

**Comment by Jak-MS** [comment]
@arkoppan @juliakm @hunyu - i have addressed the merge conflict as recommended in a previous comment. See this commit: https://github.com/MicrosoftDocs/azure-devops-docs/pull/14141/commits/024697b823009fc633d62f4ec71840c849a22ad5 

I'll merge this now... please double check that all the changes are as you intended, and if not open a new PR to address any issues. thanks.

**Comment by hunyu** [comment]
Do we know how soon PR will get published? Noticed that https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#support-for-output-variables is still dated May 2024. Or this is up to Doc Gate Keeper to officially release the update document?

**Pull request merged**
