### PR TITLE
Update sql-azure-dacpac-deployment.md

### PR DESCRIPTION
**Pull request by NandanHegde15**
Added a new Authentication method : Service Principal

### CODE REVIEW

**Comment by PRMerger12** [comment]
@NandanHegde15 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
