### PR TITLE
Git ssh caveats

### PR DESCRIPTION
**Pull request by Okeanos**
The documentation for using Git with SSH on Azure DevOps was riddled with inconsistencies (telling people URLs changed but never what the old and new URLs are), worrying recommendations (e.g. skipping fingerprint checks), unnecessary and incomplete details (how to run _some_ form of SSH Agent on Windows without establishing context as to the requirements) etc.

I attempted to fix most of these issues in various commits of this PR. Some information (e.g. the egregious values for  `HostKeyAlgorithms` and `MACs` that will trip people up a lot) could receive more attention by better placement, though.

If there is anything you would like me to change or fix please let me know and I'll take a look.

This should supersede #12372 as well.

### CODE REVIEW

**Comment by jborsecnik** [comment]
@ijayma, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Okeanos** [comment]
@jborsecnik I don't want to put an undue strain on your resources but it's been now a month since this was assigned to be reviewed and is still without feedback. Additionally, the other PR I mentioned (#12372) has been assigned to the same reviewer and has not received any feedback either (5 months later).
If there is anything I can do to expedite the review process, please let me know.

**Comment by Court72** [comment]
@vijayma 

Could you review this proposed update to your article and enter `#sign-off` in a comment if it's ready for merge?

Thanks!

**Comment by Okeanos** [comment]
This should fix #12323, #12009, #11507 (`PubkeyAcceptedAlgorithms +ssh-rsa` may not be necessary as far as I can tell), #10462.

This may also alleviate #10544 in some form because references to `bash` have been reduced to a bare minimum (Linux and Mac users will use whatever _shell_ they prefer and the Windows requirements for SSH etc. have been made more clear up front).

#11064 is obsolete with this PR because we no longer explain in detail how to handle SSH agents. That is most likely beyond the scope of this documentation I think (unless you plan on explaining vendor defaults for Linux (which distributions and agents?), macOS, and various Windows solutions.

**Comment by Okeanos** [comment]
@jborsecnik , @chcomley as you were the last to edit/touch the file I propose to update in this PR, I kindly ask that you review my changes as they remain unreviewed since early October 2022 despite having been assigned to someone. As pointed out yesterday I think these changes would fix a number of open issues.

If there is anything you would like me to change please let me know. Likewise, if you believe this PR to be (partially) obsolete please let me know so I will stop investing time here.

**Comment by Court72** [comment]
@vijayma, @mijacobs - Can you take a look at the changes in this PR?

Thanks.

**Comment by Okeanos** [comment]
@Court72 just to let you know: it's been a while and my PR concerning the Git SSH caveats for the Azure DevOps documentation is still awaiting any sort of feedback (closing in on 6 month after I raised it). I am still willing to incorporate feedback and work on the PR. Please let me know how to proceed.

**Comment by chcomley** [comment]
Hi @Okeanos, I've forwarded this PR internally, so you should have some eyes on it shortly. Thank you so much.

**Comment by Okeanos** [comment]
@chcomley just to let you know: it's been a while and I am still waiting for any sort of feedback for my PR here. It'd be very great if you could provide any sort of input on how I can proceed here.

**Comment by ShannonLeavitt** [comment]
@Okeanos - I've followed up with @chcomley via Teams. Thanks for your patience!

**Comment by chcomley** [comment]
@vijayma please review, thank you!

**Comment by steved0x** [comment]
@chcomley @Okeanos Thank you for the ping and for these edits. Let me get the right folks looking at this.

@ShannonLeavitt Can you migrate this PR to an internal PR to the private repo for review?

@Okeanos Moving your PR to our private repo (basically create a branch in our private repo and push all your commits from this PR to that branch and raising a new PR) will allow us to get the full validation and staging experience. We will keep this PR open for visibility and won't close it until we complete the review of the private PR (actually I think it will close automatically when we merge your commits there and sync them back to here)

**Comment by steved0x** [comment]
This is migrated to private repo PR https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5851 and it is in the review process. I will report back with an update.

**Comment by steved0x** [comment]
@Okeanos The updated article is live. Thank you for your updates to this article.

https://learn.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops

**Comment by chcomley** [comment]
[like]  Chrystal Comley reacted to your message:
________________________________

**Pull request merged**
