### PR TITLE
Update vstest.md

### PR DESCRIPTION
**Pull request by malpaniHMC**
The sentence was quite confusing as it could be read as inclusive or exclusive of MsTest. I now understand the wording, but it would be easier to use the word 'along' instead of 'other'.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@malpaniHMC : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@steved0x: I'm sorry - only the author of this article, @shashban, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
