### PR TITLE
#10426 Add hard size limit (384000 bytes) of Maven pom.xml files of Azure Artifacts to the documentation

### PR DESCRIPTION
**Pull request by j-tim**
Add hard size limit (384000 bytes) of Maven pom.xml files of Azure Artifacts to the documentation.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@j-tim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ramiMSFT** [comment]
@j-tim Thank you for your contribution, however your suggested change does not reflect the full picture of how Artifacts interact with POM files. We now take the uploaded POM, transform it, then apply the size limit to the transformed object. The transformed object is typically much smaller than the input.

**Comment by j-tim** [comment]
@ramiMSFT apparently there is a hard limit on pom.xml files in Azure Artifacts. 
I and many other people ran into this issue: 

```
400 Bad Request - pom.xml file is too large; the limit is 384000 bytes
```

See also: https://developercommunity.visualstudio.com/t/remove-or-increase-the-hard-limit-of-384000-bytes/809379

**Comment by electronerdian** [comment]
@j-tim I didn't see before that this PR actually predates the change ramiMSFT mentioned, which we made about a month ago. Are you still experiencing this problem?

**Comment by jmyersmsft** [comment]
@j-tim I didn't see before that this PR actually predates the change ramiMSFT mentioned, which we made last month. Are you still experiencing this problem?

**Comment by j-tim** [comment]
Hi @jmyersmsft yes I'm still experiencing this problem.

**Comment by jmyersmsft** [comment]
@j-tim is this with a private package or one from Maven Central? If the latter, can you tell me the exact group/artifact/version you're having trouble with?

**Comment by jmyersmsft** [comment]
If it's a private package, can you put the pom.xml in a zip file and tell me the size of the original POM and of the zip file?

**Comment by j-tim** [comment]
@jmyersmsft it's not a private package. It's the grand parent pom of Lucene (used by Elasticsearch) for an example of the `pom.xml` file see: https://repo1.maven.org/maven2/org/apache/lucene/lucene-solr-grandparent/8.8.1/

**Comment by jmyersmsft** [comment]
hmm... that should only be ~20KB after transformation, way under the limit. I'll have to check some things on my end.

**Comment by jmyersmsft** [comment]
Well, this is embarrassing -- we never actually turned that feature on after we deployed the code. I have begun that process. Should reach your org within a few hours to a few days from now.

**Comment by j-tim** [comment]
Thanks for the update @jmyersmsft. I'll try to run my project in the upcoming days and see whether this will fix the issue.
Just curious does this mean the hard limit of 384000 bytes for Maven pom.xml files will be gone?

**Comment by jmyersmsft** [comment]
We hit a snag while enabling it last night, so it may be a few days before it's actually on. I'll try to remember to keep this thread updated.

I believe the limit is technically still there, but the internal compressed representation is what counts, so it should allow much, much larger actual pom.xml files. For example, org.apache.lucene:lucene-solr-grandparent:8.8.1's POM shrinks from a little under 400KB to ~20KB

**Comment by j-tim** [comment]
That's great @jmyersmsft.

**Pull request closed without merging**
