### PR TITLE
Update DockerHub references to MCR.

### PR DESCRIPTION
**Pull request by msangapu-msft**
Starting July 1st, 2021 repositories from microsoft/ org on Docker Hub will be removed. At this point development, deployment and automation scripts that still reference microsoft/ org images from Docker Hub registry will fail. More information here: https://techcommunity.microsoft.com/t5/azure-developer-community-blog/deprecating-the-distribution-of-microsoft-container-images-via/ba-p/2366861

To avoid failures, I've updated the microsoft/ references to MCR. If you feel they are incorrect, please use the "Docker to MCR mapping" link below or contact us at docs-mcr-images@microsoft.com for help.

References:
Contributor's guide: https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-reference-public-container-images?branch=master
Docker to MCR mapping: https://github.com/microsoft/containerregistry/blob/master/docs/dockerhub-to-mcr-repo-mapping.md

### CODE REVIEW

**Comment by PRMerger17** [comment]
@msangapu-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@msangapu-msft - can you address the merge conflict?  after that @shashban  can take a look at the changes. Thanks.

**Comment by PRMerger16** [comment]
@msangapu-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@shashban - please review this PR.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@steved0x: I'm sorry - only the author of this article, @shashban, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
