### PR TITLE
[Android] Update Google Play tasks documentation

### PR DESCRIPTION
**Pull request by vmapetr**
This PR updates documentation for Google Play tasks.
- `GooglePlayRelease`, `GooglePlayPromote`, `GooglePlayIncreaseRollout` tasks are bumped to actual versions
- Added brief description for `GooglePlayStatusUpdate` task

### CODE REVIEW

**Comment by PRMerger4** [comment]
@vmapetr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@vijayma, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

#label:"aq-pr-triaged" 
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger12** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@vmapetr @steved0x @vijayma - because this PR adds or changes one or more :::moniker::: lines, it will need to be moved to the private repo `azure-devops-docs-pr` so we can ensure it passes validation and renders correctly on staging.

Can you move the commits?

Thanks.

If you need assistance, let us know.

**Comment by Jak-MS** [comment]
@vmapetr @steved0x - has this been replicated in the private repo?  if so, we can close this PR.  If not, it should be moved. 

If you need help with this, let us know. thanks.

**Comment by vmapetr** [comment]
> @vmapetr @steved0x - has this been replicated in the private repo? if so, we can close this PR. If not, it should be moved.
> 
> If you need help with this, let us know. thanks.

I duplicated this PR in the private repo. It can be closed now. Thanks!

**Pull request closed without merging**
