### PR TITLE
Correcting Apache Maven product name

### LINKED ISSUE #12493: Install link says `Maven Apache` instead of `Apache Maven`
**Steps to Repro**

1. Go to [Get started with Maven packages and Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven).
2. In the [Prerequisites](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=azure-devops#prerequisites) section, observe the text for the link to the download page for _Apache Maven_.

**Expected Results**
The text of the link refers to the product name as _Apache Maven_.

**Actual Results**
The text of the link is `Install Maven Apache`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 181b7f1e-c844-54ae-97b8-de3e033d9dbd
* Version Independent ID: b9e49894-7cb8-6305-01ef-983135e1c62a
* Content: [Get started with Maven packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=azure-devops#feedback)
* Content Source: [docs/artifacts/get-started-maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/get-started-maven.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

### PR DESCRIPTION
**Pull request by raydixon**
Correcting `Install Maven Apache` link text to `Install Apache Maven` to fix #12493

### CODE REVIEW

**Comment by PRMerger15** [comment]
@raydixon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@ramiMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamAntonRohm** [comment]
#sign-off

**Comment by PRMerger13** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @ramiMSFT

**Review by ramiMSFT — APPROVED** [review]

**Comment by ramiMSFT** [comment]
#sign-off

**Pull request merged**
