### PR TITLE
typo: *master

### PR DESCRIPTION
**Pull request by mcadenaroa**

### CODE REVIEW

**Comment by PRMerger5** [comment]
@mcadenaroa : Thanks for your contribution! The author(s) have been notified to review your proposed change. @azooinmyluggage

**Comment by PRMerger5** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change. @azooinmyluggage

**Review by ramiMSFT — APPROVED** [review]

**Comment by ramiMSFT** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@ramiMSFT: I'm sorry - only the author of this article, @azooinmyluggage, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger20** [comment]
@ramiMSFT: I'm sorry - only the author of this article, @azooinmyluggage, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
