### PR TITLE
options for powerShellErrorActionPreference

### PR DESCRIPTION
**Pull request by a30001539**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@a30001539 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @UshaN

**Comment by ktoliver** [comment]
@N-Usha Would you review this pull request? Thanks!

**Comment by ktoliver** [comment]
Hi @steved0x @N-Usha - Could you review the proposed update to this pipelines article? Thanks.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@steved0x: I'm sorry - only the author of this article, @UshaN, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change. @UshaN

**Pull request merged**
