### PR TITLE
Broken Link: Get feedback with Git pull requests

### PR DESCRIPTION
**Pull request by mcroley**
I believe this link would be helpful: https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops

At least it is better than a 404

### CODE REVIEW

**Comment by PRMerger12** [comment]
@mcroley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@juliakm @steved0x Could you take a look? The original article oddly shows up online, but the file isn't in the repo. 

Thanks.

**Comment by PRMerger8** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@steved0x: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
