### PR TITLE
Add a description of the "settableVariables" restriciton

### PR DESCRIPTION
**Pull request by mjroghelia**
This is a security feature introduced in M182 and agent release 2.182.1.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@mjroghelia : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
Moved to https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/2837.

**Pull request merged**
