### PR TITLE
Remove documentation suggesting integration with Service Hooks

### PR DESCRIPTION
**Pull request by stzhmsft**
Using service hooks adds unreliability to the pull request

The documentation suggests to use service hooks which adds unreliability which we have seen in customer feedback

### CODE REVIEW

**Comment by PRMerger18** [comment]
@stzhmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stzhmsft** [comment]
I'm from the team owning service hooks.

The documentation suggests to use service hooks which adds unreliability which we have seen in customer feedback

**Comment by ktoliver** [comment]
@apawast

Could you review the proposed changes to your article?

Thanks!

**Comment by ktoliver** [comment]
Review request refresh. Is the PR still in progress?

**Comment by ktoliver** [comment]
Thanks for the review, @vtbassmatt

**Pull request merged**
