### PR TITLE
Add note addressing issues when specifying a pipeline trigger from a different project

### PR DESCRIPTION
**Pull request by mslukebo**
I encountered an issue when specifying a pipeline trigger from a different project where the pipeline did not trigger. After debugging it, I noticed it started working as soon as the pipeline history showed switching the default branch from a branch without `refs/heads` to a branch with `refs/heads`. This PR adds a note about this edge case.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@mslukebo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@mslukebo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
