### PR TITLE
Remove unneeded ":" from Linux example

### PR DESCRIPTION
**Pull request by sergiuser1**
No need to add the column to the `MY_PAT` variable since the next line adds it.

### CODE REVIEW

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by Court72** [comment]
Hi @steved0x 

PRMerger will accept sign-off from the listed author only. However, if you are a Microsoft employee authorized to update this content, you can send a request to [techdocprs@microsoft.com](mailto:techdocprs@microsoft.com) for this PR to be merged. Include your role and an explanation of why the PR should be merged without approval from the listed author.

Thanks!

**Review by steved0x — APPROVED** [review]

**Comment by Court72** [comment]
@steved0x - it looks like resolving the merge conflict resulted in this PR having no changes. If that's correct, go ahead and enter a `#please-close` comment. Thanks!

**Comment by steved0x** [comment]
#please-close

**Pull request closed without merging**
