### PR TITLE
fix(ssh-auth): include host key algorithms as well

### PR DESCRIPTION
**Pull request by jsburckhardt**
Details:
- running in ubuntu20.04
- git version 2.34.1

Following the instructions in the doco didn't allow me to fetch new changes. I had to add the `HostkeyAlgorightms` to the git config as well.

Test:
- issue
  image

- fix:
  image

### CODE REVIEW

**Comment by PRMerger13** [comment]
@jsburckhardt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@vijayma - Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger7** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by steved0x** [comment]
This one is fixed in private repo PR https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5851

**Pull request closed without merging**
