### PR TITLE
Process model is per project, not per organization

### PR DESCRIPTION
**Pull request by fingineering**
Afaik, the *process model* can be chosen at project level,  not only at organization level, at least in Azure DevOps Services. Not sure about collection in ADO Server. 

Changed the wording accordingly in line 12.

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@fingineering : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@KathrynEE 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger6** [comment]
@KathrynEE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by KathrynEE — APPROVED** [review]

**Comment by KathrynEE** [comment]
#sign-off

**Pull request merged**
