### PR TITLE
Completion of the lab is first dependent on creating a Service Connec…

### PR DESCRIPTION
**Pull request by gamcmaho**
…tion of type ARM

To ensure your Azure DevOps project has the needed authorization through to your Azure Subscription, create a Service Connection of type ARM.  This will be required when creating a pipeline within the project to deploy to Azure Kubernetes Service.  Otherwise the dropdown lists for Cluster and Container Registry are empty.  Please insert detailed instructions or link to an appropriate doc to avoid our customers bumping into the same.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@gamcmaho : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @azooinmyluggage - Would you review the proposed update to your article?

If you approve the pull request, the PR review team can edit the update for grammar and Microsoft style before merging the PR. Thanks.

**Review by azooinmyluggage — APPROVED** [review]

**Comment by ktoliver** [comment]
@azooinmyluggage It looks like the contributor's branch has been deleted, so I can't edit the commit or move it in a way that the contributor is acknowledged for their contribution. "ARM" isn't allowed in the repo in this context. I'll check with the lead PR reviewer to see how to proceed.

**Comment by ktoliver** [comment]
We'll merge this and then submit a follow-up PR that has an edited version of the new paragraph. The paragraph seems somewhat out of place at the start of the Prerequisites section, given the bulleted list items that appear in the include files in that section. Perhaps a future review is warranted.

**Pull request merged**
