### PR TITLE
removed duplicate sprint 178

### PR DESCRIPTION
**Pull request by michha**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@michha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Sid-ah** [comment]
@ktoliver, we will be updating and moving all work items to the appropriate quarter.

**Comment by ktoliver** [comment]
> @ktoliver Kristine Toliver (Aquent LLC) Vendor, we will be updating and moving all work items to the appropriate quarter.

@Sid-ah Thanks. Would you like to keep the pull request open or close it at this time?

**Comment by michha** [comment]
@Sid-ah To play it safe. My PR is just about removing duplicate lines about sprint 178 in the timeline and doesn't affect the section "Features under development"
image

**Review by Sid-ah — APPROVED** [review]

**Comment by ktoliver** [comment]
Thanks @michha. Merging per approval by @Sid-ah.

**Pull request merged**
