### PR TITLE
added an example on debug logs in YAML

### PR DESCRIPTION
**Pull request by ymakkapati**
For the YAML file, the debug variable can be set in variable section as shown below.

variables:
  System.Debug: true

### CODE REVIEW

**Comment by PRMerger15** [comment]
@ymakkapati : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@steved0x 

Could you review the proposed changes to your article?

Thanks!

**Comment by steved0x** [comment]
@ymakkapati Thank you for your contribution, it should be live soon.

**Comment by steved0x** [comment]
#sign-off

**Comment by steved0x** [comment]
#hold-off

**Comment by PRMerger19** [comment]
@ymakkapati : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
