### PR TITLE
Update Splunk URL

### PR DESCRIPTION
**Pull request by Official-James**
input- is not needed in the URL, if used it fails to connect. There must also be a port specified which is not visible in the URL used to access Splunk. The default is 8088

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Official-James : Thanks for your contribution! The author(s) have been notified to review your proposed change. @roferg

**Comment by ktoliver** [comment]
Hi @chcomley - Could you review the proposed update? Also, should the metadata **author** value be changed to your GitHub account name? It's currently set to the Microsoft alias `roferg`. Thanks.

**Comment by ktoliver** [comment]
@chcomley for review

Thanks.

**Review by chcomley — APPROVED** [review]

**Comment by PRMerger9** [comment]
@chcomley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chcomley** [comment]
#sign-off

**Pull request merged**
