### PR TITLE
Clarified information

### PR DESCRIPTION
**Pull request by jpmicrosoft**
Clarified information to reflect that a service connection does not need to have contributor access to a subscription but it can also be dialed down to a resource group and added periods.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@jpmicrosoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@RoopeshNair Could you review this pull request? Thanks.

**Comment by ktoliver** [comment]
@RoopeshNair

**Comment by ktoliver** [comment]
Hi @KaycoinsInc - Thanks for your review. We do need a member of the Microsoft content team or a Microsoft PM to review and approve the PR before merging. Thanks!

**Comment by KaycoinsInc** [comment]
Thank you

**Pull request closed without merging**
