### PR TITLE
Update azure-sqldb.md

### PR DESCRIPTION
**Pull request by RecursiveGeek**
Make Powershell script parameters consistent, Cleanup

### CODE REVIEW

**Comment by PRMerger13** [comment]
@RecursiveGeek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@ramiMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger14** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ramiMSFT** [comment]
#sign-off

**Pull request merged**
