### PR TITLE
Bjanousek patch 1

### PR DESCRIPTION
**Pull request by bjanousek**
This is to update the documentation for the Mermaid diagrams as per what's supported in M211.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@chcomley 
- Can you review this PR?
- there's enough changes in this PR that it should be either moved to the private repo or reopened there. Can you move it?  (let us know if you'd like assistance) 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by chcomley** [comment]
Hi @Jak-MS, thank you. Reviewed and approved. I would appreciate your assistance with moving it, if possible. Thanks so much.

**Comment by chcomley** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@chcomley - https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5168

**Comment by jborsecnik** [comment]
@chcomley, can you resolve the conflicts that have arisen so we can move this over to the private repo? Thanks.

**Comment by jborsecnik** [comment]
> @chcomley, can you resolve the conflicts that have arisen so we can move this over to the private repo? Thanks.

Ignore previous comment. I didn't realize this has already been moved.

**Pull request closed without merging**
