### PR TITLE
Update billing-faq.yml

### PR DESCRIPTION
**Pull request by drewbren**
Updates to the Billing FAQ to:
1) remove temporary language that is now outdated (referring to the business model changes in 2019)
2) remove references to the VS Marketplace, since ADO is no longer purchased via the marketplace 
3) add how to pay for Azure DevOps Server

### CODE REVIEW

**Comment by American-Dipper** [comment]
@chcomley - can you review the proposed changes?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Review by chcomley — APPROVED** [review]

**Comment by Court72** [comment]
@cchomley, 

Thanks for reviewing! Before this PR can be merged, the validation errors need to be resolved. The commits should also be moved to the private repo for staging. Let us know if you'd like the PR review team's help moving the commits.

**Comment by chcomley** [comment]
@Court72, I've advised my PM to use the private repo from now on and would love your help in moving this over, thank you so much.

**Comment by Jak-MS** [comment]
@drewbren @chcomley - this has been moved to private here: https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/6309

**Pull request closed without merging**
