### PR TITLE
Update add-external-user.md

### PR DESCRIPTION
**Pull request by AlexandraRamirezMS**
Customers need a specific permission in AAD if they are guests of the tenant

### CODE REVIEW

**Comment by PRMerger6** [comment]
@AlexandraRamirezMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @AlexandraRamirezMS - If you work within the Microsoft network, you should link your GitHub account with your Microsoft account. Let me know if you need information about how to do this; I can email it to your Microsoft alias.

**Comment by ktoliver** [comment]
@chcomley - Hi, could you review the proposed update to your article? Thanks.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chcomley — APPROVED** [review]

**Comment by chcomley** [comment]
#sign-off

**Pull request merged**
