### PR TITLE
Updated the URL proposed to manage Service Connections.

### PR DESCRIPTION
**Pull request by ArielMorales**
The correct URL is: `https://dev.azure.com/{organization}/{project}/_settings/adminservices`
Instead of: `https://dev.azure.com/{organization}/{project}/adminservices`

### CODE REVIEW

**Comment by PRMerger15** [comment]
@ArielMorales : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@RoopeshNair - Could you review the proposed update to your article? Thanks.

**Comment by ktoliver** [comment]
@steved0x @RoopeshNair - Could you review the proposed changes to this pipelines article? Thanks.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
