### PR TITLE
update transforms-variable-substitution.md doc fixes issue #6563

### PR DESCRIPTION
**Pull request by lpacis**
Added example of variable substitution in appsettings.json, changed the webapp deploy task to be simplier for documentation.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@lpacis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by lpacis** [comment]
Was not able to link the issue, but PR addresses https://github.com/MicrosoftDocs/azure-devops-docs/issues/6563

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
