### PR TITLE
Update dotnet-client-libraries to use modern grammar.

### PR DESCRIPTION
**Pull request by Anduin2017**
Fix some document formatting issue. Use `string` instead of `String`

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Anduin2017 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chcomley** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@Anduin2017 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chcomley** [comment]
#sign-off

**Pull request merged**
