### PR TITLE
Clarify the usage of a service connection for Azure RG deployment task

### PR DESCRIPTION
**Pull request by brianveltman**
Clarify the usage of a service connection instead of Azure subscription.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@brianveltman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks, all.

**Pull request merged**
