### PR TITLE
Corrected Path Issue for NuGet Caching

### PR DESCRIPTION
**Pull request by mitchelsellers**
The provided documentation samples for how to cache NuGet packages does not work with the current Azure DevOps Hosted Agent environments.  Updated the documentation to reference `$(UserProfile)` instead which does work successfully.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@mitchelsellers : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@steved0x @ramiMSFT - Could you review this pipelines pull request? If approved, I can resolve the merge conflict.

**Review by kaycoinsUSA — APPROVED** [review]

**Review by steved0x — APPROVED** [review]

**Comment by PRMerger17** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@steved0x: I'm sorry - only the author of this article, @ramiMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
