### PR TITLE
Update create-a-readme.md

### PR DESCRIPTION
**Pull request by giraffesyo**
I added a couple lines as tips for providing build steps to developers.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@giraffesyo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by vtbassmatt** [comment]
This is good stuff, thank you.

#sign-off

**Review by vtbassmatt — APPROVED** [review]

**Comment by vtbassmatt** [comment]
(And there have been several times where I've wished I followed your last bit of advice 🤣 )

**Comment by jborsecnik** [comment]
@vtbassmatt, is this approved to merge? Thanks.

**Comment by vtbassmatt** [comment]
@jborsecnik did I do it wrong? When `#sign-off` didn't work, I tried hitting the "Approve" button. Should I have gone ahead and merged it myself?

**Comment by jborsecnik** [comment]
Probably it was fine. I just wasn't 100-percent clear if it was ready to merge now. (We usually do the merge, after a quick editorial check.)  Thanks.

**Pull request merged**
