### PR TITLE
Code checks if variable is empty

### PR DESCRIPTION
**Pull request by alexs77**
Title was "Run if variable is **null**". In the example, `testNull` was assigned an empty string.

YAML spec at https://yaml.org/spec/1.2/spec.html#id2803362 states:

> Note that a null is different from an empty string.

The change changes the section name and variable name to better reflect what's actually done.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@alexs77 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@juliakm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
#sign-off

**Comment by juliakm** [comment]
@alexs77 I made a small change to resolve a conflict.

**Pull request merged**
