### PR TITLE
Adding information on how to renew a client secret for auto generated SPN via service connection

### PR DESCRIPTION
**Pull request by MS-alsulli**
Many customers don't know that a client secret can be renewed for an auto generated SPN / service connection. The UI doesn't have a "secret" section for SPNs that were created using the "Automatic" method during the service connection creation process. It is as simple as clicking two buttons to renew the secret.

Added information on how to do this the ARM endpoint doc.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@MS-alsulli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@MS-alsulli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chcomley — APPROVED** [review]

**Comment by chcomley** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@chcomley: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
