### PR TITLE
replace TFS with Azure DevOps Server

### PR DESCRIPTION
**Pull request by shayki5**
Since TFS name is changes to Azure DevOps Serve I fixed the docs with the new name.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@shayki5 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
