### PR TITLE
Update approvals.md for Check policy compliance

### PR DESCRIPTION
**Pull request by v-abiss**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@v-abiss : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#assign juliakm

**Comment by steved0x** [comment]
#unassign steved0x

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@juliakm: I'm sorry - only the author of this article, @shashban, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
