### PR TITLE
Fix typo in DotNetCLI publish heading example

### PR DESCRIPTION
**Pull request by Izzmo**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Izzmo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @pulkitaggarwl - Could you review this pull request? Thanks.

**Comment by Izzmo** [comment]
@pulkitaggarwl any updates on this?

**Comment by ktoliver** [comment]
@mijacobs Hi, is there someone on your team who can review this pull request from January? Thanks.

**Pull request merged**
