### PR TITLE
These two pages appear to have the titles mixed up

### PR DESCRIPTION
**Pull request by flcdrg**
- Swap titles so they match the page content and filenames

### CODE REVIEW

**Comment by PRMerger20** [comment]
@flcdrg : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@steved0x: I'm sorry - only the author of this article, @shashban, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
