### PR TITLE
Note premium plan requirement

### PR DESCRIPTION
**Pull request by SeanFeldman**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@SeanFeldman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@SeanFeldman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SeanFeldman** [comment]
@anthonychu it would be good to include an important prerequisite/note about Consumption not being supported.

**Review by steved0x — APPROVED** [review]

**Comment by PRMerger3** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
@SeanFeldman Thank you for your contribution. This article has moved out of the Azure DevOps docset and into the Azure docset, here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops?tabs=dotnet-core%2Cyaml%2Ccsharp#deploy-a-container

I can't move this PR since it is a different repo and the content is owned by a different team. If your issue about premium plan requirement isn't resolved in the new article content in the new repo, please raise a PR or a GH issue there. Thank you.

**Comment by SeanFeldman** [comment]
@steved0x the article you've linked to is pointing to https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image, which does now mention the following:

> Deploying your function code in a custom Linux container requires [Premium plan](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan) or a [Dedicated (App Service) plan](https://docs.microsoft.com/en-us/azure/azure-functions/dedicated-plan) hosting. 

So no other action is necessary. 

On a side note, it's sad to see a minor PR such as this that could help others not to waste their time, sit on a bench for 7 months(!) just to be closed because documentation got shuffled. It definitely doesn't encourage anyone to send PRs and begs a question why to even bother to have an edit button.
image

**Pull request closed without merging**
