### PR TITLE
Update multi-repo-checkout.md

### PR DESCRIPTION
**Pull request by proudmonkey**
Typo on line 165. Change `MyAzureReposGitRepo` to `MyAzureReposGitRepository`

### CODE REVIEW

**Comment by PRMerger15** [comment]
@proudmonkey : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
@proudmonkey I made a tweak and I am merging this PR, thank you for your contribution!

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
