### PR TITLE
Typo "**Time **Criticality"→”**Time** Criticality”

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/changes-to-process-templates?view=azure-devops
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger16** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hyoshioka0128** [comment]
#PingMSFTDocs

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
It looks like the term should be bold, so I've made that change and will merge. Thanks!

**Pull request merged**
