### PR TITLE
Remove "Set up the build task" section from SourceLink doc

### LINKED ISSUE #12436: set-up-the-build-task step is unnecessary in SourceLink doc
I think the set-up-the-build-task step is unnecessary in the SourceLink documentation. This step says to set the SourceLinkCreate property to true (via `/p:SourceLinkCreate=true` on the MSBuild command line).

As far as I can tell, it has no effect on whether SourceLink is included or not in the final build.

By default, once they've added the appropriate Microsoft.SourceLink NuGet package from the preceding step, users shouldn't need to control SourceLink inclusion manually. The Microsoft.SourceLink NuGet packages automatically determine whether SourceLink should be enabled.

Users _can_ override the default behavior -- perhaps to disable SourceLink completely in certain build flavors -- but it's done via a different property: EnableSourceLink

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb2bfcb-0a0c-ce90-fa49-ad2e7fbaa57a
* Version Independent ID: 1a295877-ff8f-f8c2-0349-76a69a0f5cfc
* Content: [Publish symbols with Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops#set-up-the-build-task)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

### PR DESCRIPTION
**Pull request by pharring**
Fixes #12436

### CODE REVIEW

**Comment by PRMerger20** [comment]
@pharring : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@ramiMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by pharring** [comment]
@ramiMSFT can you sign off on this please?

**Comment by PRMerger18** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ramiMSFT — APPROVED** [review]

**Comment by ramiMSFT** [comment]
@pharring Thank you for your contribution!

#sign-off

**Pull request merged**
