### PR TITLE
Adding nested Object each loop

### PR DESCRIPTION
**Pull request by JFolberth**
Adding nested Object each loop.

Trying to be consistent with: https://github.com/MicrosoftDocs/azure-devops-docs/pull/12997

### CODE REVIEW

**Comment by Court72** [comment]
@juliakm 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by JFolberth** [comment]
@juliakm just bumping this PR

**Comment by juliakm** [comment]
@JFolberth  Thanks! This worked well for me.

**Comment by juliakm** [comment]
#sign-off

**Review by juliakm — APPROVED** [review]

**Pull request merged**
