### PR TITLE
Update add-custom-wit.md

### PR DESCRIPTION
**Pull request by AlexandraRamirezMS**

### CODE REVIEW

**Comment by ktoliver** [comment]
@KathrynEE Could you review the proposed update to your article? The quality criteria for the repository includes no links to images that are hosted elsewhere; images need to be added to the repository to be referenced in an article. I can help move this update to the private repo and create screenshots, if needed. Thanks.

**Review by KathrynEE — COMMENTED** [review]
Not approved for reasons stated in the comments.

**Comment by KathrynEE** [comment]
@AlexandraRamirezMS - Thank you for suggesting this update. However, I need to close this PR as not approved for the following reasons: 
 1. Updates such as this one require you make them in the regular **azure-devops-docs-pr** repo and not the public repo. 
 2. The images need work and need to conform to the format that we need.  
 3. We have content already that illustrates how to update the backlog levels, [Customize your backlogs or boards (Inheritance process)](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-backlogs-boards?view=azure-devops). 

I agree that the current article, [Add a custom work item type](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/add-custom-wit?view=azure-devops), would benefit from having additional information for adding the custom work item type to a backlog level. However, I think that would best be done with a smaller content footprint through one or more Q&A's at the end of the article. I can work on that update and add you to the review. 

If there is some other problem that you are trying to solve with the addition of this content, please reach out to me. 

Thanks, Kathryn

@ktoliver - fyi

**Comment by AlexandraRamirezMS** [comment]
Hi,
A smaller content footprint through one or more Q&A's at the end of the article is OK.

Thank you very much!

Best Regards,
Alexandra Ramírez
SUPPORT ENG
Azure DevOps
Office: +(52)5580565821
***@***.******@***.***>
09AM - 06 PM CST
[Microsoft ***@***.***D735FE.DBCAB820]
Backup Engineer : ***@***.******@***.***>
Manager : ***@***.******@***.***>

**Pull request closed without merging**
