### PR TITLE
Update inheriting-permissions-from-other-AADs AB#1760414

### PR DESCRIPTION
**Pull request by v-abiss**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@v-abiss : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by v-abiss** [comment]
AB#1760414

**Review by chcomley — APPROVED** [review]

**Comment by PRMerger17** [comment]
@chcomley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @chcomley - Could you review my edit for accuracy? I don't see a reference to this new bookmark in the repo, so revising the anchor name should be OK and not break anything. Thanks.

**Review by chcomley — APPROVED** [review]

**Comment by ktoliver** [comment]
Thanks.

**Pull request merged**
