### PR TITLE
Fix for Singular folder names rather than plural #1564

### LINKED ISSUE #1564: Singular folder names rather than plural
consider aligning with standard gitflow naming and use singular rather than plural folder names e.g. bugfix, release and feature rather than bugfixes, releases and features. more letters, longer branch names, more typing = :( 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 330532da-d568-b010-a154-62afb1844e4a
* Version Independent ID: 4efad37d-4ec2-033e-51b1-b9f588e675c6
* Content: [Require branches to be created in folders](https://docs.microsoft.com/en-gb/vsts/repos/git/require-branch-folders?view=vsts&tabs=vsts-tfs-web-portal)
* Content Source: [docs/repos/git/require-branch-folders.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/require-branch-folders.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

### PR DESCRIPTION
**Pull request by NenoLoje**
This is to fix #1564 and rename:
- features/ --> feature/
- releases/ --> release/
- No changes to users/

### CODE REVIEW

**Comment by PRMerger9** [comment]
@NenoLoje : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by NenoLoje** [comment]
@apawast Any updates this one?

**Comment by NenoLoje** [comment]
@apawast ?

**Comment by ktoliver** [comment]
@chcomley @ramiMSFT Would one of you be able to review the proposed changes? Thanks.

@apawast

**Comment by ktoliver** [comment]
@chcomley Thanks for the review.

**Pull request merged**
