### PR TITLE
Documentation Tweaks for Creating a Build Task

### PR DESCRIPTION
**Pull request by mindlessroman**
Going through this process for myself and came across a few tweaks that should happen for clarity. Personally one for verbosity :D

### CODE REVIEW

**Comment by PRMerger19** [comment]
@mindlessroman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@mindlessroman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@mindlessroman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chcomley — APPROVED** [review]

**Comment by PRMerger20** [comment]
@mindlessroman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chcomley — APPROVED** [review]

**Comment by PRMerger8** [comment]
@mindlessroman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
