### PR TITLE
Update dotnet-core-cli.md

### PR DESCRIPTION
**Pull request by dariogriffo**
if zipAfterPublish is not set, make sure we know the ziped folder is deleted (been debugging something for 3 hours)

### CODE REVIEW

**Comment by PRMerger19** [comment]
@dariogriffo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Note that publishing in this repository is suspended until Tuesday, May 19. Merging will resume at 7:00 AM PT Tuesday. Authors can still review and sign off on PRs during this time. Thanks.

**Comment by dariogriffo** [comment]
any update on this?

**Comment by ktoliver** [comment]
@pulkitaggarwl - Could you review the proposed update to your article? Thanks.

**Comment by ktoliver** [comment]
@steved0x @pulkitaggarwl - Could you review this pull request? If the update is approved, I can resolve the merge conflict.

**Review by steved0x — APPROVED** [review]

**Comment by PRMerger16** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@steved0x: I'm sorry - only the author of this article, @pulkitaggarwl, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@steved0x - I see your pull request reviews and approvals in the repo and will merge them shortly. Thanks!

**Pull request merged**
