### PR TITLE
Added clarification for the nuget package needed for Coverlet code coverage

### PR DESCRIPTION
**Pull request by dahlsailrunner**
When trying to get a Linux-based build for an ASP.NET Core web project (implementing IdentityServer4) and it took a while to figure out why I wasn't getting code coverage results published.  There are a few options for coverlet NuGet packages, and I mistakenly chose `coverlet.coverage`.  This change just adds a clarification that indicates the correct NuGet package to use to get this working.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@dahlsailrunner : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
#sign-off

Thanks @dahlsailrunner! That's a very helpful addition.

**Comment by ktoliver** [comment]
Hi @dahlsailrunner - Thank you for your contribution. Would you take a moment to sign the Contributor License Agreement (CLA)? After the CLA is signed, then we can merge your update. Thanks!

**Comment by ktoliver** [comment]
Admin note: This PR has been added to the bug in https://ceapex.visualstudio.com/Engineering/_workitems/edit/168950. The bug reports a known issue in which the CLA agent reports a false positive until/unless a subsequent commit is added to the PR.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dahlsailrunner** [comment]
Signed!   Thanks.  :)

**Comment by ktoliver** [comment]
Thanks @dahlsailrunner

**Pull request merged**
