### PR TITLE
Update expressions.md

### PR DESCRIPTION
**Pull request by dciborow**
Provide a useful example of how to use convertToJson with Bash. See this issue here. https://stackoverflow.com/questions/57264556/prevent-quotes-from-disappearing-in-json-in-between-azure-devops-tasks/70967584?noredirect=1#comment125795408_70967584

### CODE REVIEW

**Comment by PRMerger9** [comment]
@dciborow : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@dciborow : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger16** [comment]
@dciborow : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dciborow** [comment]
Even better fix provided. The correct way here is to use single quotes instead of double qoutes.

**Comment by juliakm** [comment]
Thanks @dciborow! 

#sign-off

**Comment by SimonAlling** [comment]
> The correct way here is to use single quotes instead of double qoutes.

No, it just happens to work more often because double quotes are more common than single quotes in JSON. The real solution is to pass the JSON to the program as _data_ instead of using it as part of the _source code_ of the program. Please see [my comment](https://github.com/MicrosoftDocs/azure-devops-docs/issues/11983#issuecomment-1125092780) on #11983 as well as my suggested improvement in #12312.

**Pull request merged**
