### PR TITLE
1 user suggests update the Azure Pipelines agents overview document

### PR DESCRIPTION
**Pull request by AlexChongMicrosoft**
The customers who are making secondary development, want to know the behavior of DevOps agents when the pipeline jobs are cancelled.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@AlexChongMicrosoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @AlexChongMicrosoft - Would you take a minute to sign the Contributor License Agreement (CLA)? Then we can complete the review of the pull request. Thanks!

**Comment by steved0x** [comment]
#sign-off

**Comment by ktoliver** [comment]
@AlexChongMicrosoft Thanks for contributing to the documentation. Would you take a moment to sign the Contributor License Agreement (CLA) for contributing? Commits added to the pull request in review of your proposed content addition moved the pull request into CLA-check status, and it looks like you haven't signed one for this repository. After you sign the CLA, we can merge the pull request. Thanks.

**Comment by PRMerger13** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AlexChongMicrosoft** [comment]
> @AlexChongMicrosoft Thanks for contributing to the documentation. Would you take a moment to sign the Contributor License Agreement (CLA) for contributing? Commits added to the pull request in review of your proposed content addition moved the pull request into CLA-check status, and it looks like you haven't signed one for this repository. After you sign the CLA, we can merge the pull request. Thanks.

Hi, thanks for your reply. I have done the CLA. Maybe in the future, I will raise some other udpate request. Look forward to contributing more.

**Pull request merged**
