### PR TITLE
Add troubleshoot for TeamServicesAgent/TeamServicesAgentLinux vm extension

### PR DESCRIPTION
**Pull request by tejasd1990**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@tejasd1990 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by bishal-pdMSFT — APPROVED** [review]

**Comment by ktoliver** [comment]
@bishal-pdMSFT Thanks for your review. In the public repo, the article author, another member of the content team, or a(nother) PM needs to approve updates before merging. Thanks.

@RoopeshNair @steved0x @juliakm Could one of you review the update to a pipelines article?

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@steved0x: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
