### PR TITLE
Delete rm-endpoint-link.png

### PR DESCRIPTION
**Pull request by arkoppan**
Deleting the old screenshot for Service Connection (manual).

Will  upload a new screenshot.

### CODE REVIEW

**Comment by arkoppan** [comment]
rm-endpoint-link

**Comment by arkoppan** [comment]
rm-endpoint-link

**Comment by ktoliver** [comment]
@juliakm @RoopeshNair Could you review the proposed update (file deletion)? Thanks.

**Comment by juliakm** [comment]
#sign-off

**Review by juliakm — APPROVED** [review]

**Comment by ktoliver** [comment]
Hi @arkoppan - Have you submitted a replacement image in a new or follow-up pull request? The image is referenced in docs/pipelines/library/connect-to-azure.md, so it seems like deleting the image from the repo will create a missing-image indicator on the live article. Thanks.

**Comment by ktoliver** [comment]
#hold-off pending confirmation of replacement image file

**Review by ktoliver — CHANGES_REQUESTED** [review]
@arkoppan Could you let us know whether an image to replace this one that's being deleted was submitted? Thanks.

**Comment by steved0x** [comment]
@ktoliver I'm closing this one since we haven't gotten a response with a replacement image.

**Pull request closed without merging**
