### PR TITLE
Remove duplicate `config_file_location`

### PR DESCRIPTION
**Pull request by glenchao**
There's already a `config_file_location` definition down below. The description also doesn't seem to make sense.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@glenchao : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@steved0x 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger7** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
