### PR TITLE
Update PublishBuildArtifactsV1.md

### PR DESCRIPTION
**Pull request by phillipsj**
Correcting typo in the property name.

### CODE REVIEW

**Comment by ktoliver** [comment]
@vijayma This include file appears to be used in your article https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops. Could you review the proposed change? Thanks.

**Comment by Jak-MS** [comment]
@vijayma - bump. can you take a look? thanks.

**Comment by ktoliver** [comment]
@steved0x Do you think someone on the content team could review this PR from February? The update looks fine to me, but I'm not able to verify it. Thanks.

**Comment by ktoliver** [comment]
LGTM.

**Pull request merged**
