### PR TITLE
Update content-trust.md

### PR DESCRIPTION
**Pull request by Luperi**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Luperi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@azooinmyluggage Could you take a look at this pull request? Thanks.

**Review by azooinmyluggage — APPROVED** [review]

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks @azooinmyluggage

**Pull request merged**
