### PR TITLE
Added resources trigger related variables

### PR DESCRIPTION
**Pull request by esecules**
Fixes MicrosoftDocs/azure-devops-docs#9266

### CODE REVIEW

**Comment by PRMerger17** [comment]
@esecules : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by esecules** [comment]
Could someone confirm I got the correct variable capitalization? I tried `Resources.TriggeringAlias` in my pipeline and it seemed to work, but it doesn't match with the existing camelCase theme. I couldn't get the right capitalization from `env` because in bash all the variable names are uppercase only.

**Comment by ktoliver** [comment]
@juliakm - Hi, will you take a look at the proposed changes to your article? Thanks.

**Comment by juliakm** [comment]
@esecules Thanks for the PR! The correct syntax is `resources.triggeringAlias`.

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
