### PR TITLE
Make it simple to add the public key.

### PR DESCRIPTION
**Pull request by focusonmx**
There is a few change of UI in Azure Devops. So the explanation to add the public key must be changed.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@focusonmx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by focusonmx** [comment]
I think the image of explanation must be changed, too. How can I change the image?

**Comment by vtbassmatt** [comment]
You can add images right in the repo; look in `media/use-ssh-authentication` for the ones used in this topic.

We should moniker this so that down-level versions of TFS/Azure DevOps on-premises get correct information. You can do that like this:

```markdown
::: moniker range=">= azure-devops-2019"
(Content that applies to the new UI)
::: moniker-end

::: moniker range="< azure-devops-2019"
(Content that applies to the old UI)
::: moniker-end
```

**Comment by PRMerger16** [comment]
@focusonmx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by vtbassmatt — APPROVED** [review]

**Comment by ktoliver** [comment]
I'd like to move this commit to the private repo to verify the moniker formatting changes on staging. The contributor association with the update will be retained. @vtbassmatt Is that OK with you?

**Comment by ktoliver** [comment]
We moved the commit to https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/2114 in the private repository. The new PR will be merged this afternoon. We'll close this PR.

**Pull request closed without merging**
