### PR TITLE
Updates compatibility notes for ##vso[release.updatereleasename]

### PR DESCRIPTION
**Pull request by jessehouwing**
`##vso[release.updatereleasename]` is supported as of Azure DevOps Server 2020.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoftdocs/azure-devops-docs/9489)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@jessehouwing : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by vtbassmatt** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@vtbassmatt: I'm sorry - only the author of this article, @juliakm, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by vtbassmatt** [comment]
Well then, robot, I guess I'll let @juliakm sign off on it 😁

**Comment by jessehouwing** [comment]
Haha poor Matt!

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
> Well then, robot, I guess I'll let @juliakm Julia Kulla-Mader FTE sign off on it 😁

A close match, but I think @vtbassmatt won in the end. Thanks for your review.

**Pull request merged**
