### PR TITLE
Adding detail for public project regarding power bi support

### PR DESCRIPTION
**Pull request by ksmis-gh**
Adding detail for public project regarding power bi support, due to a customer ticket.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@ksmis-gh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ksmis-gh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chcomley — COMMENTED** [review]
Hi, Thanks for your input - what's AX please? Thanks!

**Comment by PRMerger8** [comment]
@ksmis-gh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ksmis-gh** [comment]
> Hi, Thanks for your input - what's AX please? Thanks!

@chcomley Thanks for the feedback! Removed the term

**Review by chcomley — APPROVED** [review]

**Pull request merged**
