### PR TITLE
Update v2-windows.md

### PR DESCRIPTION
**Pull request by PavloAndriiesh**
Update agent creation docs in order to make sure agents folder should be editable by admins only.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@PavloAndriiesh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@PavloAndriiesh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger19** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by steved0x — APPROVED** [review]

**Pull request merged**
