### PR TITLE
Changed the syntax for the add extension to the correct one, was miss…

### PR DESCRIPTION
**Pull request by simonlid**
Added a new bash variable to contain the region as this is referenced in the key vault secrets section
Added a hyphen to name parameter in the az add extension code for the azure-devops extension
Changed the line continuation on the key vault secrets to allow the code to be copied more easily

### CODE REVIEW

**Comment by PRMerger16** [comment]
@simonlid : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@simonlid : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@simonlid : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
Thanks @simonlid!

#sign-off

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
