### PR TITLE
Default macOS-latest image has changes

### PR DESCRIPTION
**Pull request by ArthurBrum**
Azure is now using macOS-latest image as macOS-12

### CODE REVIEW

**Comment by ArthurBrum** [comment]
Can someone help me double check? But this is what seems to be happening now

**Comment by Jak-MS** [comment]
@steved0x 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by steved0x** [comment]
@ArthurBrum It looks like it has rolled out for some people, let me confirm and I will get this merged. Thank you.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
