### PR TITLE
Note OAuth token support can be silently disabled

### PR DESCRIPTION
**Pull request by yirkha**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@yirkha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by chcomley — APPROVED** [review]

**Comment by chcomley** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
