### PR TITLE
Divais 168changes

### PR DESCRIPTION
**Pull request by divais**
multi-tenant and admin support doc amends

### CODE REVIEW

**Comment by PRMerger16** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @divais - 

PMs and content developers should work in the private repositories as described in [Should I work in a private or a public repo?](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=master) The private repo for azure-devops-docs is at https://github.com/MicrosoftDocs/azure-devops-docs-pr (add "-pr" to the URL if you edit direct from the repository).

In the private repos, your content gets the benefit of quality validation, and you can verify it on staging before publishing. Some PRs that have fewer updates might qualify for auto-merge.

(If you want a member of the content team to review your updates in the private repo before merging, you can request a review or at-mention them in a comment before you sign off. See [GitHub for content reviews](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-reviews?branch=master).)

Would you create a pull request in the private repo to make these updates? We'll close this PR. Thank you!

**Comment by divais** [comment]
@ktoliver 
Thank you for sharing the guidance. I will need to redo all the changes in the 6 files, can this PR be approved and will ensure to follow these steps going forward? Or do share if there is a way to move all changes to -pr repository?

Thank you for your consideration.

**Comment by ktoliver** [comment]
Hello @divais - There _is_, in fact, a process for doing that, and it's described in [Pull public commits to the private repo for updates, staging, publication](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=master#pull-public-commits-to-the-private-repo-for-updates-staging-publication). The PR review team can move your commit to the private repo--does that sound OK? I'll do that now and post the new PR info here, then close this PR. Thanks.

**Comment by ktoliver** [comment]
@divais To access the commit, I might need to change the PR from draft mode to ready. Will try this...

**Comment by ktoliver** [comment]
This commit has been moved to the private repo, PR https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1243. We'll close this PR. Thank you

**Comment by divais** [comment]
> Hello @divais - There _is_, in fact, a process for doing that, and it's described in [Pull public commits to the private repo for updates, staging, publication](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=master#pull-public-commits-to-the-private-repo-for-updates-staging-publication). The PR review team can move your commit to the private repo--does that sound OK? I'll do that now and post the new PR info here, then close this PR. Thanks.

THANKS a lot!!

**Pull request closed without merging**
