### PR TITLE
Update Linux SHA firewall FAQ

### PR DESCRIPTION
**Pull request by ShachafGoldstein**
Update Linux SHA firewall FAQ to include https://vstsagentpackage.azureedge.net for updates to agent

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ShachafGoldstein : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ShachafGoldstein : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @steved0x Would you take a look at this pull request? Thanks!

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by ktoliver** [comment]
@steved0x Thanks for your PR reviews today. 👍

**Pull request merged**
