### PR TITLE
Added issue resolution docs for IndexedDb rules bug

### PR DESCRIPTION
**Pull request by ctmayn**

### CODE REVIEW

**Review by davekenn — APPROVED** [review]

**Comment by ktoliver** [comment]
@KathrynEE Could you recommend a reviewer from the content team for this new article? The article and file name don't meet all PR quality criteria (they must meet the same criteria as if being merged in the private repo), so some modifications will need to be made if it's approved/accepted. 

Thanks.

**Comment by KathrynEE** [comment]
@ktoliver - I'm the person to review this as I cover Azure Boards content. 
@ctmayn - I'm going to close this PR without merging. We always appreciate contributions from the product team to our content. However, we request that you add them to the private repo, azure-devops-docs-pr. Also, in this case, it's best if you reach out to one of the content devs, such as myself, to make sure that you are following the guidance in our [Contributors Guide](https://review.docs.microsoft.com/en-us/help/contribute/?branch=master).   

In this case, I'd like to take charge of getting the new content added as it warrants inclusion in several places. I'll include you in the review of the PR if that works for you. We can get this done by EOD today or tomorrow. One question, if the user takes the action specified here, [Refresh or reevaluate permissions](https://docs.microsoft.com/en-us/azure/devops/organizations/security/troubleshoot-permissions?view=azure-devops#refresh-or-reevaluate-permissions), will that fix the problem?

**Comment by ctmayn** [comment]
@KathrynEE Thanks for taking a look at this. I tried reaching out to you on Slack and your GitHub email last week but didn't receive a response from either. For the future, what channels should I reach out to you?

As for your question, unfortunately no, doing that does not fix the issue.  Even if their permissions are completely up to date on the server-side, this issue will still affect them if they have the evaluated rules already cached.

**Comment by KathrynEE** [comment]
@ctmayn - Sorry I didn't respond to your message. I'm not really active on Slack. I usually pick up my GitHub emails, particularly if they are tied to a repo. I'm active on Teams and of course regular email.

**Pull request closed without merging**
