### PR TITLE
Adding an additional option for preserving VC tags and labels

### PR DESCRIPTION
**Pull request by StingyJack**
ref https://github.com/MicrosoftDocs/azure-devops-docs/issues/8692  

The H1/# in the middle is the only way I could figure out for displaying a "gotcha". It needs that kind of emphasis, but another attention getting convention is OK

### CODE REVIEW

**Comment by PRMerger15** [comment]
@StingyJack : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by StingyJack** [comment]
@ktoliver - wasn't trying to wreck the structure or format, available options are limited since GH won't take a font tag in md.

> The H1/# in the middle is the only way I could figure out for displaying a "gotcha". It needs that kind of emphasis, but another attention getting convention is OK

**Comment by juliakm** [comment]
Just thinking that we could use a note. One of these markdown options could work:

```
> [!NOTE]
> Information the user should notice even if skimming.

> [!IMPORTANT]
> Essential information required for user success.

> [!CAUTION]
> Negative potential consequences of an action.
```

**Comment by PRMerger14** [comment]
@StingyJack : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by StingyJack** [comment]
trying the caution element, no idea what it looks like though.

**Comment by ktoliver** [comment]
@StingyJack On the live site, it renders like this [example](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-mutual-certificates#add-a-key-vault-certificate):

image

**Comment by ktoliver** [comment]
@juliakm Could you have another look? Thanks.

**Comment by juliakm** [comment]
Looks good. Thanks @StingyJack and @ktoliver!

#sign-off

**Comment by ktoliver** [comment]
Thank you!

**Pull request merged**
