### PR TITLE
Fix Uri

### PR DESCRIPTION
**Pull request by eslamisepehr**
There was an extra "/" after the quotation mark.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@eslamisepehr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger4** [comment]
@eslamisepehr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chcomley** [comment]
Thanks @eslamisepehr!

#sign-off

**Pull request merged**
