### PR TITLE
Add a note about triggers on non-default branch to resources.md

### PR DESCRIPTION
**Pull request by yevheniy-solovey-ms**

### CODE REVIEW

**Comment by Court72** [comment]
@juliakm

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by yevheniy-solovey-ms** [comment]
I don't know if the comment was for me, but here it is.

#sign-off

**Comment by Court72** [comment]
Thanks @yevheniy-solovey-ms. The [comment](https://github.com/MicrosoftDocs/azure-devops-docs/pull/14105#issuecomment-2250811547) was for the article's author, @juliakm.

**Comment by juliakm** [comment]
#sign-off

**Pull request merged**
