### PR TITLE
docs: add ssh usage docs for go get

### PR DESCRIPTION
**Pull request by artbegolli**
Signed-off-by: Art Begolli <artbegolli@gmail.com>

Updates docs for using `go get` with SSH. This means you will not have to create a specific PAT for `go get` and also removes the `_git` from module path as the ssh path is being used instead.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@artbegolli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@vtbassmatt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by vtbassmatt** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
