### PR TITLE
clarify auto-complete functionality

### PR DESCRIPTION
**Pull request by evandigby**
I would not expect auto-complete to require "optional" policies by default. I propose clarifying the documentation in this regard.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@evandigby : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by vtbassmatt** [comment]
This isn't true, or at least isn't globally true. We have optional policies in our own repo and autocomplete doesn't wait on them. In fact, some can even fail and autocomplete still works.

@evandigby are you still experiencing this? There might be a setting I'm unaware of (new to the policies area, despite a long history with the Git server).

**Comment by ktoliver** [comment]
Hi @vtbassmatt Do you want to keep this pull request open? Thanks.

**Comment by vtbassmatt** [comment]
@ktoliver it can be closed.

**Pull request closed without merging**
