### PR TITLE
described how to get an up to date local 

### PR DESCRIPTION
**Pull request by stuartm9999**
Get a clean local source repo from remote and make sure you have the branches  you want to migrate
 #9906

### CODE REVIEW

**Comment by PRMerger18** [comment]
@stuartm9999 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by vtbassmatt** [comment]
There are some issues with this topic, but to my reading, this PR doesn't address them. The instructions already include `git clone --mirror`, which fetches everything. To push everything, we suggest `git push --mirror` (though only in a screenshot -- should be spelled out directly).

Among the other issues: there's discussion about "because it's a bare repo" that doesn't add anything and the screenshots are out of date.

**Comment by Jak-MS** [comment]
@vtbassmatt - do you want to keep this PR open?  Thanks.

**Comment by stuartm9999** [comment]
The ```git clone --mirror``` ensures the new repo gets all your changes from the local repo.  This issue I found was that when I cloned  my old repo to local, the local only had the main branch so only that ended up in the new repo.
This makes perfect sense, as I believe the process mirrors the local repo to "MigrationDemo" - but I had to do these extra steps to make sure my local repo had all the branches I wanted in the new repo.
But if you don't think it adds anything or makes sense - go ahead and close the pr

**Comment by vtbassmatt** [comment]
@stuartm9999 I think I see now, thank you. `git clone --mirror` does the right thing if you're making a fresh clone, but we don't really give that as background info. It sounds like you read it as using `git clone --mirror` in an existing clone of your repo.

If you want to fix the instructions and update this PR, that's fine. Otherwise, you can close it (or ask @Jak-MS to do so) and someone on our side can fix #9906 in a new PR.

**Comment by stuartm9999** [comment]
Ah - so I should've started with a git clone --mirror <source remote url>?  I've a couple more repos to migrate over the next while so I'll try this in anger an re-write my PR - thanks for the clarifiaction.

**Comment by vtbassmatt** [comment]
Thanks! And to be clear, I don't think it's your job to rewrite the PR -- only if you want to 😁 If not, someone from our team can do it.

**Comment by stuartm9999** [comment]
Thanks

**Pull request closed without merging**
