### PR TITLE
Add yamlschema endpoint link

### LINKED ISSUE #8248: yaml schema file
There's an endpoint in DevOps REST API that provides YAML schema: https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/yamlschema?view=azure-devops-rest-5.1
It should be mentioned in docs here (the schema in vscode extension can get outdated).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

### PR DESCRIPTION
**Pull request by qbikez**
For people that are searching for 'azure pipelines template YAML schema', show a way to obtain latest schema. 
Closes #8248

### CODE REVIEW

**Comment by PRMerger13** [comment]
@qbikez : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@steved0x - If the update is approved, the PR review team can remove the locale from the URL that's added. Thanks.

**Comment by PRMerger20** [comment]
@qbikez : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by vtbassmatt** [comment]
@qbikez thanks for your contribution. The trouble with adding that line to the doc is that you can't do anything meaningful with the generated schema (yet). It's my hope to get the VS Code extension updated so that it can accept a custom schema, but we haven't done that work yet.

**Comment by ktoliver** [comment]
@vtbassmatt @qbikez Should the pull request be closed, or would you like to keep it open for now? Thanks.

-PR review team

**Comment by vtbassmatt** [comment]
@ktoliver whoops, good catch! I've updated the VS Code extension so it accepts additional schema files. We can merge this!

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
