### PR TITLE
Canary update - added full YAML

### PR DESCRIPTION
**Pull request by vermegi**
This update describes how to perform a canary update to k8s using a single YAML pipeline and environments for the approval gate. It sits next to the split YAML - Classic Release pipeline which was already there.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@vermegi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @azooinmyluggage - Could you review the proposed changes to your article?

The addition of tabbed content, if it's approved, should be tested in the Microsoft Docs staging environment before being published. To test on staging, the PR will need to be moved or resubmitted in the private repo. The contributor can either [Join the MicrosoftDocs organization](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-github?branch=master#join-microsoftdocs-organization-and-others) and resubmit the update in a new PR in the azure-devops-docs-pr repo, or, after approval from the content team, the PR review team can move the commit to the private repo and open a new PR there. Thanks!

**Comment by vermegi** [comment]
I will be resubmitting on the private repo.

**Comment by ktoliver** [comment]
@vermegi Thanks!

**Pull request closed without merging**
