### PR TITLE
Add note that publishWebProjects defaults to true

### PR DESCRIPTION
**Pull request by markrendle**
Just added a single sentence ("Note that this argument defaults to true if not specified.") to the `publishWebProjects` argument entry.

I lost an hour to this today. On [this guide page](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#publish-artifacts-to-azure-pipelines) there's a big purple note:

image

But on the [.NET Core CLI task "reference" page](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops) it doesn't mention it at all.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@markrendle : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@pulkitaggarwl @steved0x Could you review this community contribution from April? 

Thank you!

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@steved0x: I'm sorry - only the author of this article, @pulkitaggarwl, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
