### PR TITLE
add-external-user.md: Use backticks instead of double quotes

### PR DESCRIPTION
**Pull request by bergmeister**
This makes it stand out better visually and easier to copy-paste the email subject to search for it.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@bergmeister : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger15** [comment]
@chcomley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chcomley** [comment]
#sign-off

**Pull request merged**
