### PR TITLE
Added other open-source load testing alternatives

### PR DESCRIPTION
**Pull request by ppcano**
Added open-source load testing tools that support scripting: Artillery, Gatling, k6, and Locust.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@ppcano : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#reassign pboramsft

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
