### PR TITLE
Note that "project" can be the name, not just GUID

### PR DESCRIPTION
**Pull request by 50Wliu**
Either that, or all the examples are wrong :D.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@50Wliu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
@50Wliu Thank you for letting us know. I am merging this PR, and I will check to see if allowing the project name was a new addition, and if so when it was added, so I can document that.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@steved0x: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
