### PR TITLE
Fix a link in landing page

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by ktoliver** [comment]
@KathrynEE - Could you review the proposed change to the hub page?

cc/ @mijacobs @steved0x

**Comment by KathrynEE** [comment]
@ktoliver, @Youssef1313 - This change would introduce a broken link. 
Not approved. 
cc/ @mijacobs @steved0x

**Comment by ktoliver** [comment]
@KathrynEE - Yes. If you chose to make that content change, `/get-started/` would need to be removed from the URL.

**Comment by KathrynEE** [comment]
@ktoliver - I noticed a duplicate link entry which I've removed with this PR: https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1329.

**Comment by ktoliver** [comment]
Awesome. 👍

**Pull request closed without merging**
