### PR TITLE
Graceful Agent Cleanup

### PR DESCRIPTION
**Pull request by mozts2005**
added updates to docker startup scripts to allow the agent to auto unregister from the agent pool when the docker container is shutdown.

- removed token file delete
- change Linux to use the run.sh that is provided with the agent installer and to follow windows pattern.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@mozts2005 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mozts2005** [comment]
ETA?

**Comment by ktoliver** [comment]
@steved0x - Could you review the proposed update to your article?

Thanks.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
@mozts2005 Thank you for your changes to this article, they should be live later today. Happy holidays!

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
