### PR TITLE
Clarification on percentage calculation on the Progress report

### PR DESCRIPTION
**Pull request by RTudosa**
As detailed on internal task (https://mseng.visualstudio.com/AzureDevOps/_workitems/edit/1972442) 
Related to doc bug (https://mseng.visualstudio.com/AzureDevOps/_workitems/edit/1952871) and DTS (https://mseng.visualstudio.com/AzureDevOps/_workitems/edit/1952589)

### CODE REVIEW

**Comment by Jak-MS** [comment]
@steved0x - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by RTudosa** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@steved0x @mijacobs - nudging for a review of this pr. thanks.

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
