### PR TITLE
Syntax fix and whitespace cleanup

### PR DESCRIPTION
**Pull request by Olivier-Lemay-Dostie**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@steved0x 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by steved0x — APPROVED** [review]

**Comment by Jak-MS** [comment]
@Olivier-Lemay-Dostie - can you resolve the merge conflict(s)?

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by Olivier-Lemay-Dostie** [comment]
@Jak-MS I'm not sure I have the rights to see the conflicts as I don't see them.

**Pull request merged**
