### PR TITLE
Adding section stage depending in job output

### PR DESCRIPTION
**Pull request by mariussm**
The following example would have saved me several hours of trying and failing

### CODE REVIEW

**Comment by PRMerger13** [comment]
@mariussm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
@mariusstrom Thanks for your contribution! I wasn't able to get your code sample working and made a couple changes. Can you look this over? 

```yaml
stages:
- stage: plan_dev
  jobs:
  - job: terraform_plan_dev
    steps:
    - bash: echo '##vso[task.setvariable variable=terraform_plan_exitcode;isOutput=true]2'
      name: terraform_plan
- stage: apply_dev
  dependsOn: plan_dev
  condition: eq(dependencies.plan_dev.outputs['terraform_plan_dev.terraform_plan.terraform_plan_exitcode'], '2')
  jobs:
  - job: part_b
    steps:
    - bash: echo "BA"
```

**Comment by mariusstrom** [comment]
@juliakm I think you meant to tag @mariussm (who also has a pretty awesome first name 👍 )

**Comment by juliakm** [comment]
@mariussm Can you take a look at the updated code sample when you have a chance?

**Comment by juliakm** [comment]
#sign-off

**Review by juliakm — APPROVED** [review]

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
