### PR TITLE
Update Azure Stack Hub target for AzureDev Ops

### PR DESCRIPTION
**Pull request by mattbriggs**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@mattbriggs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@mattbriggs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@mattbriggs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@mattbriggs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @mattbriggs - This pull request was opened in the public repo. Could you move it to the private repo, so the updates can benefit from the quality checks there? Thanks!

**Comment by mattbriggs** [comment]
@ktoliver Ah! This explains so much. Thanks for noting this. Moving it now.

**Pull request closed without merging**
