### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by tbonez88**

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @KathrynEE Is this a pull request you can review? Thanks.

**Comment by KathrynEE** [comment]
@ktoliver - This is NOT approved. This introduces a file and folder for what purpose I don't know. If this person is a Microsoft person, then they should be working in the private repo.

**Comment by ktoliver** [comment]
@tbonez88 Would you like to provide more information about your pull request?

**Comment by ktoliver** [comment]
#hold-off

**Comment by ktoliver** [comment]
@KathrynEE Should this pull request from last November remain open and pending?

Thanks.

**Comment by KathrynEE** [comment]
@ktoliver - no, I think we should close this. Doing so now.

**Pull request closed without merging**
