### PR TITLE
Update description of SymbolsFolder

### PR DESCRIPTION
**Pull request by qsharker**
SymbolsFolder is not supporting UNC paths. Update the description.

### CODE REVIEW

**Comment by ktoliver** [comment]
@steved0x @PBoraMSFT - Could you review this pipelines pull request? Thanks.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@steved0x: I'm sorry - only the author of this article, @PBoraMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
