### PR TITLE
Update servicenow.md

### PR DESCRIPTION
**Pull request by jhuitu**
The supported version info has not been updated, it currently missing New York (and maybe Orlando too(?))

### CODE REVIEW

**Comment by PRMerger9** [comment]
@jhuitu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@azooinmyluggage Could you review this pull request? If you don't want to list the versions that are not supported, maybe we could change the text string to "The integration is compatible with Kingston and later versions of ServiceNow" for clarity. Please check. Thanks.

**Comment by juliakm** [comment]
#sign-off 

I see support for New York mentioned on the [marketplace documentation](https://marketplace.visualstudio.com/items?itemName=ServiceNow.vss-services-servicenow-devops&ssr=false#overview). There are two more updates since this PR. I'll follow-up to see if those are also valid.

**Comment by PRMerger20** [comment]
@juliakm: I'm sorry - only the author of this article, @azooinmyluggage, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
