### PR TITLE
Fix: Pipeline publish path incorrect

### LINKED ISSUE #9959: Pipeline publish path incorrect
In `copyFiles` tasks source folder is set to `$(system.defaultworkingdirectory)/target/azure-functions/`, this produces build as 
image

however, azure functions do not populate because of an extra folder.

coreect build artifact should be:

image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e576b8-a378-a985-33cb-8adb9d7d7957
* Version Independent ID: d1b99713-8e01-23d9-47b7-1a9b5c98d5ca
* Content: [Build and deploy a Java web app to Azure Functions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java-function?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/java-function.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/java-function.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

### PR DESCRIPTION
**Pull request by ankur198**
This would resolve #9959.

I have added a variable for functiomAppName and used it while copyTask to get correct build artifacts

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ankur198 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@ankur198 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by juliakm** [comment]
#sign-off

**Comment by juliakm** [comment]
#sign-off

**Pull request merged**
