### PR TITLE
Add example of using private PowerShell repository in Azure Pipelines

### PR DESCRIPTION
**Pull request by AdrianSanguineti**
Added an example of how to use Azure Artifacts as a private PowerShell repository from a YAML Azure Pipeline. The example is based off a pipeline I'm using in a private project.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@AdrianSanguineti : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger9** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ramiMSFT — APPROVED** [review]

**Comment by ramiMSFT** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
