### PR TITLE
Changed "Release title" to "Title" for consistency

### PR DESCRIPTION
**Pull request by icnocop**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@icnocop : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@vijayma Would you review the proposed change to your article? Thanks.

**Comment by vijayma** [comment]
@steved0x Can you help me track down the author of this. (It is not me). @shashban, would you know and can you check this PR?

**Comment by ktoliver** [comment]
@vijayma is currently the author listed in the article metadata. It might need to be updated; automated notification works on the metadata `author` value.

image

**Comment by shashban** [comment]
@raiyanalam can help

**Comment by raiyanalam** [comment]
Thanks for raising this PR!  Nice catch. The current 'Release title' is actually the label  we show in the designer pipeline. However it seems that the equivalent YAML for this is just 'title', which is a mismatch. Changing the name of parameter in the task would potentially need a major version bump up. We have taken a note of this suggestion and will update the task if others users also report similar problems. 
Closing this for now. Thanks for the suggestion!
 [@ktoliver -please close this]

**Comment by ktoliver** [comment]
@raiyanalam Thanks for your review!

**Pull request closed without merging**
