### PR TITLE
Added missing powershell code example

### PR DESCRIPTION
**Pull request by fajterini**
Added missing PowerShell code example in Set an output variable for use in future stages part. 
Only Bash example is present.

### CODE REVIEW

**Comment by fajterini** [comment]
@microsoft-github-policy-service agree

**Comment by American-Dipper** [comment]
@juliakm - can you review the proposed changes?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by juliakm** [comment]
Thanks @fajterini! Your code sample worked for me. 
#sign-off

**Review by juliakm — APPROVED** [review]

**Comment by juliakm** [comment]
#sign-off

**Review by juliakm — APPROVED** [review]

**Comment by juliakm** [comment]
#sign-off

**Comment by juliakm** [comment]
#sign-off

**Comment by fajterini** [comment]
Thanks

**Pull request merged**
