### PR TITLE
Typo "team explorer"→"Team Explorer"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/get-code-reviewed-vs?view=azure-devops
https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/tfvc/get-code-reviewed-vs.md
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger3** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@steved0x: I'm sorry - only the author of this article, @MaximMalygin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
