### PR TITLE
Make list of appTypes include workflowapp for Single Tenant Logic Apps

### PR DESCRIPTION
**Pull request by Stijn-Rutten**
Make list of appTypes include workflowapp for Single Tenant Logic Apps

### CODE REVIEW

**Comment by Stijn-Rutten** [comment]
As described in the following article: https://docs.microsoft.com/en-us/azure/logic-apps/set-up-devops-deployment-single-tenant-azure-logic-apps?tabs=azure-devops
```
- task: AzureFunctionApp@1
  displayName: 'Deploy logic app workflows'
  inputs:
     azureSubscription: 'MyServiceConnection'
     appType: 'workflowapp'
     appName: 'MyLogicAppName'
     package: 'MyBuildArtifact.zip'
     deploymentMethod: 'zipDeploy'
     ```

**Comment by Jak-MS** [comment]
@azooinmyluggage @mijacobs 
- Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
#assign: @mijacobs

**Comment by juliakm** [comment]
#sign-off

**Comment by juliakm** [comment]
#unassign-reviewer:azooinmyluggage

**Review by juliakm — APPROVED** [review]

**Comment by juliakm** [comment]
#sign-off

**Comment by steved0x** [comment]
@Stijn-Rutten Thank you for your contribution. We just published a new task reference that went live about the same time as your PR. The new task reference is built from the task [open source repo here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureFunctionAppV1/task.json#L47), and AzureFunctionApp@1 (and it looks like a v2 might be coming soon) don't list workflowapp as one of the choices and so it doesn't display in the task assistant for YAML pipelines or the classic editor for classic pipelines. Here is the new page for this task - I can add a note to that input parameter that is equivalent to your PR here.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v1?view=azure-pipelines#inputs

**Pull request merged**
