### PR TITLE
Remove errant attribute in example syntax

### PR DESCRIPTION
**Pull request by SeanKilleen**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@SeanKilleen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@SeanKilleen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Looks good; I made a small edit to match the code snippet earlier in the article (`path to the transform`). Merging now.

**Pull request merged**
