### PR TITLE
Add a hint to use minimatch patterns

### PR DESCRIPTION
**Pull request by MarkIannucci**
helps #3268

### CODE REVIEW

**Comment by PRMerger6** [comment]
@MarkIannucci : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@vijayma 

Could you review the proposed changes to your article?

Thanks!

**Comment by ktoliver** [comment]
@vijayma (refresh notification)

**Comment by ktoliver** [comment]
@steved0x Could you review this pipelines pull request? Thanks.

**Review by steved0x — APPROVED** [review]

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@steved0x: I'm sorry - only the author of this article, @vijayma, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
